---
title: "Monitor de Salud Escolar"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    social: menu
    theme: simplex
runtime: shiny
---

```{r message=FALSE, results='hide', warning=FALSE}
# Load packages
library(flexdashboard)
library(rio)
library(here)
library(tidyverse)
library(REDCapDM)
library(anthroplus)
library(rspiro)
library(rspiro)
library(finalfit)

# data_shiny <- import(here("data", "data_shiny.rds"))

data_shiny <- readRDS("D:/Academic/Nutritional epidemiology projects/CAUSAS_CVD/data/data_shiny.rds")

data_shiny <- data_shiny |>
  dplyr::select(
    record_id, ansiedad_1, ansiedad_2, depresion_1, depresion_2, PHQ_9,
    depresion, PHQ_9, depresion, GAD_7, ansiedad, afhc_score, dinamometria,
    categoria_afhc, paqc_final_score, paqc_dx,
    
    alergia_pteronyssinus, alergia_farinae, alergia_destructor, 
    alergia_tropicalis, alergia_perro, alergia_germanica, asma, rinitis_alergica,
    feno,
    
    asma_vida, asma_actual, asma_severa, rinitis_actual, rinoconjuntivitis, 
    eczema_actual,
    
    glucosa, trigliceridos, hdl_colesterol, colesterol_total, PAS, PAD, pulso,
    metabolic_health, TG_HDL_dx, bp_category, crit_tg, crit_hdl, crit_glucosa,
    
    sexo_factor, edad_anios, peso_kg, talla_m, peso_kg, imc, zbfa_dx, zhfa_dx,
    pliegue_bicipital, pliegue_tricipital, pliegue_subescapular, perimetro_cuello,
    
    grasa_boileau, grasa_slaughet, grasa_deurenberg, grasa_ict, grasa_ip,
    
    fvc_maximo, fev1_maximo, pef_maximo, fev1_fvc_ratio, interpretacion_espiro)

# Función auxiliar para determinar colores de alerta
get_color <- function(valor, tipo) {
  if(tipo == "colesterol") return(ifelse(valor > 200, "danger", "success"))
  if(tipo == "riesgo") return(ifelse(valor == "Saludable", "success", "warning"))
  return("primary")
}
```

# Report {data-orientation="rows"}

## Inputs {.sidebar}
=====================================

```{r}
selectInput(
  "nino_seleccionado",
  label = "Seleccione el nombre del niño:",
  choices = unique(data_shiny$record_id))

hr() # Línea horizontal

# Botón de descarga
h4("Exportar Resultados")
helpText("Descargue un informe detallado para entregar a los padres.")

radioButtons("format", "Formato de documento:", c("Word (.docx)" = "docx", "PDF (.pdf)" = "pdf"), inline = TRUE)

downloadButton("descargar_reporte", "Generar Informe")
```

```{r}
# --- LÓGICA REACTIVA ---

# Filtrar datos según el niño seleccionado
datos_nino <- reactive({
  req(input$nino_seleccionado)
  data_shiny %>% filter(Nombre == input$nino_seleccionado)
})

# Manejador de descarga
output$descargar_reporte <- downloadHandler(
  filename = function() {
    paste0("Informe_Salud_", gsub(" ", "_", input$nino_seleccionado), "_", Sys.Date(), ".", input$format)
  },
  content = function(file) {
    # Crear un entorno temporal para pasar las variables al reporte
    tempReport <- file.path(tempdir(), "reporte_padres.Rmd")
    
    # Copiar la plantilla al directorio temporal
    # Asegúrate de tener el archivo 'reporte_padres.Rmd' en la misma carpeta que este script
    file.copy("reporte_padres.Rmd", tempReport, overwrite = TRUE)
    
    # Parámetros a pasar al Rmd
    params <- list(
      nino = input$nino_seleccionado,
      datos = datos_nino()
    )
    
    # Renderizar
    rmarkdown::render(tempReport, output_file = file,
                      params = params,
                      output_format = ifelse(input$format == "pdf", "pdf_document", "word_document"),
                      envir = new.env(parent = globalenv()))
  }
)
```


Row

### Diagnóstico General

```{r}
renderValueBox({
  d <- datos_nino()
  valueBox(d$TG_HDL_dx, 
           icon = "fa-user-md",
           color = get_color(d$TG_HDL_dx, "Alto"))
})
```

### Índice de Masa Corporal (IMC) {data-height=350}

```{r}
renderValueBox({
  d <- datos_nino()
  valueBox(d$imc, 
           icon = "fa-weight",
           color = ifelse(d$imc > 25, "warning", "success"))
})
```   
    
### Salud Mental

```{r}
renderValueBox({
  d <- datos_nino()
  valueBox(d$ansiedad_1, 
           icon = "fa-brain",
           color = ifelse(d$ansiedad_1 == "Estable", "info", "warning"))
})
```

Row {data-height=650}

## Perfil Lipídico y Presión Arterial