---
title: "Pilot_results"
format: pptx
editor: source
---

## Load packages

```{r}
# Packages
pacman::p_load(
  rio,
  here, 
  janitor,
  tidyverse,
  REDCapR,
  REDCapDM,
  rfextras,
  gtsummary,
  Hmisc,
  anthroplus,
  rspiro,
  childsds,
  pedbp
)

# Scripts
source(here::here("scripts", "PAQ-C_item_9.R"))
```

## Import data

```{r}
#| include: false
# Read REDCap data
source(here::here("scripts", "credentials.R"))

# Transformation of raw data into factors (labels)
proyecto_procesado <- rd_transform(proyecto_redcap)

# Extract the data frame
data <- proyecto_procesado$data

# Variable labels
source(here::here("scripts", "labels.R"))

# Check
head(data, 10)
```

## Process data

```{r}
#| include: false
data_clear <- data |>
  mutate(
    
    # Sexo
    sexo = case_when(
      record_id %in% c(
        "001 - Rihana Fabiola Ajalcriña Tejada",
        "003 - Grace Alcabuino Hermoza",
        "004 - Flavia Ajalcriña Tejada",
        "010 - Yomayra Genesis De la O",
        "013 - Yadira Romero Nacazama",
        "014 - Saskia Zatalaya Bustos",
        "015 - Sofia Perez Canturini",
        "016 - Daniela Palma Cruz",
        "018 - Areliz Chuquimbalqui Maza",
        "020 - Domenica Figueroa Rodriguez",
        "022 - Cielo Guadalupe Pariñas Carranza",
        "023 - Orianka Crespin Ruiz",
        "024 - Ghia Mujica Encizo",
        "025 - Mia Guillen Flores",
        "026 - Jheynny Arirama Amante",
        "027 - Naomi Reyes Napam",
        "031 - Briyith Amasifuen Castro",
        "032 - Anahi Mia Anhuaman",
        "033 - Kiara Chuquizuta Ramos",
        "034 - Alice Matsufiji Cordova",
        "035 - Emyly Huaranga Pobes",
        "040 - Danna Paucar Quispe",
        "041 - Maria Enco Santiesteban",
        "043 - Azumi Trujillo Quilca",
        "045 - Yamilee Torres Choceña",
        "046 - Taewa Cachay",
        "047 - Mia Flores Vallejos",
        "048 - Samantha Valeria Vásquez Fernández",
        "050 - Maylen Mariel Garcia Vilcarromero",
        "052 - María F. Soles Castro",
        "053 - Luana Maciel Rojas Rivera",
        "054 - Noemi Mercedes Ruiz Grijalua",
        "057 - Lyla Huaycama Huertas",
        "058 - Angela Rosario Palomares Marín",
        "059 - Anyolith Sunmi Mayta De la Cruz",
        "060 - Yasumi Viviana Guevara Huantongori",
        "061 - Amy Alessandra Salinas Huaccache",
        "066 - Sara Rojas Salazar",
        "067 - Isis Cabrera Fernandez",
        "068 - Andrea Yanayaco Amao",
        "069 - Francheska Quispe Sánchez",
        "070 - Xiomara Rihana Maira Quispe Espinoza",
        "071 - Anahi Reyna Torrejon",
        "073 - Karen Paola Sandoval Facundo",
        "074 - Dayana Nicole Yarasca Castillos",
        "075 - Maryori Remigio Alfaro",
        "076 - Nahomi Tarazona Ponce"
      ) ~ 2,
      record_id %in% c(
        "002 - Percy Rojas Canchari",
        "005 - Aldair Dayiro Contreras Cutamanca",
        "006 - Frank Yensi Julan Pinedo",
        "007 - Fabiano Puchuni Espinoza",
        "008 - Maycol Fernandez Huaman",
        "009 - Pedro Machuca Sanchez",
        "011 - Duban Huaman Carrillo",
        "012 - Diego Mamani Chipani",
        "017 - Jordan Usurin Sarmiento",
        "019 - Moises Enmanuel Ancajima Ybarra",
        "021 - Angel de Jesus Vilela Amamsifuen",
        "028 - Cristian Solis Veliz",
        "029 - Caleb Casabona Vega",
        "030 - Alessandro Tito Toscano",
        "036 - Jann Oliver Estevan Echevarria",
        "037 - Daniel Reyes Santi",
        "038 - Evan Rojas Rojas",
        "039 - Thiago Huarcaya Huaman",
        "042 - Roy Huaron Aranda",
        "044 - Bryan Setalaya Canales",
        "049 - Mathias Adriano Castillo Taipe",
        "051 - Jael Cruz Isidro",
        "055 - Matias Córdova Hancco",
        "056 - Erick Santiago Huaccache Gómez",
        "062 - José María Dylan Núñez Chuchon",
        "063 - Enrique Cruz Luque",
        "064 - Santiago Espinoza Yucra",
        "065 - Jesús Tapullima Chonote",
        "072 - Ameht Paulo Quispe"
      ) ~ 1,
      TRUE ~ NA_real_), 
    sexo_factor = fct_recode(as.character(sexo), "Masculino" = "1", "Femenino" = "2") |>
      fct_relevel("Masculino", "Femenino"),
    
    # Edad
    edad_anios = coalesce(edad_adolescente, 11),
    edad_meses = edad_anios * 12,
    
    # Peso
    peso_kg = rowMeans(across(c(
      peso_1, peso_2, peso_3
    )), na.rm = TRUE),
    
    # Talla
    talla_cm = rowMeans(across(c(
      talla_1, talla_2, talla_3
    )), na.rm = TRUE),
    talla_m = talla_cm / 100,
    
    # Pliegues
    pliegue_bicipital = rowMeans(across(
      c(
        pliegue_bicipital_1,
        pliegue_bicipital_2,
        pliegue_bicipital_3
      )
    ), na.rm = TRUE), 
    
    pliegue_tricipital = rowMeans(across(
      c(
        pliegue_triceps_1, 
        pliegue_triceps_2, 
        pliegue_triceps_3
      )
    ), na.rm = TRUE), 
    
    pliegue_subescapular = rowMeans(across(
      c(
        pliegue_subescapular_1,
        pliegue_subescapular_2,
        pliegue_subescapular_3
      )
    ), na.rm = TRUE), 
    
    # Perimeters/circumferences
    perimetro_cuello = rowMeans(across(
      c(
        perimetro_cuello_1, 
        perimetro_cuello_2, 
        perimetro_cuello_3
      )
    ), na.rm = TRUE),
    
    perimetro_cintura = rowMeans(across(
      c(
        perimetro_cintura_1,
        perimetro_cintura_2,
        perimetro_cintura_3
      )
    ), na.rm = TRUE), 
    
    perimetro_cadera = rowMeans(across(
      c(
        perimetro_cadera_1, 
        perimetro_cadera_2, 
        perimetro_cadera_3
      )
    ), na.rm = TRUE), 
    
    # Indices
    glucosa_mmol = glucosa / 18.01,
    trigliceridos_mmol  = trigliceridos / 88.57,
    hdl_mmol = hdl_colesterol / 38.67,
    imc = peso_kg / (talla_m^2),
    indice_ponderal = peso_kg / (talla_m^3),
    indice_cintura_talla = perimetro_cintura / talla_cm,
    indice_cintura_cadera = perimetro_cintura / perimetro_cadera,
    TyG = log((trigliceridos * glucosa) / 2), 
    VAI = case_when(
      sexo == "Masculino" ~ (perimetro_cintura / (39.68 + (1.88 * imc))) * 
        (trigliceridos_mmol / 1.03) * (1.31 / hdl_colesterol),
      sexo == "Femenino"  ~ (perimetro_cintura / (36.58 + (1.89 * imc))) * 
        (trigliceridos_mmol / 0.81) * (1.52 / hdl_colesterol),
      TRUE ~ NA_real_
    ),
    TyG_WC = TyG * perimetro_cintura,
    TyG_BMI = TyG * imc,
    TyG_WHtR = TyG * indice_cintura_talla,
    TG_HDL = trigliceridos / hdl_colesterol,
    
    TyG_WC_q4 = ntile(TyG_WC, 4),
    TyG_BMI_q4 = ntile(TyG_BMI, 4),
    TyG_WHtR_q4 = ntile(TyG_WHtR, 4),
    TG_HDL_q4 = ntile(TG_HDL, 4),
    
    # Sumatoria de pliegues (TR + SE)
    suma_pliegues = (pliegue_tricipital + pliegue_subescapular) / 2,
    
    # Estimación del % de Grasa Corporal (%GC) - Ecuación de Boileau et al. (1985)
    grasa_boileau = case_when(
      sexo_factor == "Masculino" ~ 1.35 * suma_pliegues - 0.012 * (suma_pliegues^2) - 4.4,
      sexo_factor == "Femenino"  ~ 1.35 * suma_pliegues - 0.012 * (suma_pliegues^2) - 4.2,
      TRUE ~ NA_real_
    ),
    
    # Masa Grasa en Kg
    masa_grasa_kg_boileau = (grasa_boileau / 100) * peso_kg,
    
    # Estimación del %GC - Ecuación de Slaughetr et al. (1988)
    grasa_slaughet = case_when(
      sexo_factor == "Masculino" ~ 0.783 * suma_pliegues + 1.6,
      sexo_factor == "Femenino"  ~ 0.546 * suma_pliegues + 9.7,
      TRUE ~ NA_real_
    ),
    
    # Masa Grasa en Kg
    masa_grasa_kg_slaughet = (grasa_slaughet / 100) * peso_kg,
    
    # Variable de sexo codificada para Deurenberg (Hombres=1, Mujeres=0)
    sexo_deurenberg = case_when(
      sexo == 1 ~ 1,
      sexo == 2 ~ 0,
      TRUE ~ NA_real_
    ),
    
    # Estimación del %GC - Ecuación de Deuremberg et al.(1991)
    grasa_deurenberg = (1.51 * imc) - (0.70 * edad_anios) - (3.6 * sexo_deurenberg) + 1.4,
    
    # Masa Grasa en Kg
    masa_grasa_kg_deurenberg = (grasa_deurenberg / 100) * peso_kg,
    
    # Estimación del %GC - Ecuación 1 de Urra et al. (2021)
    grasa_ict = case_when(
      sexo == 1 ~ 9.775 + (0.415 * suma_pliegues) + (35.084 * indice_cintura_talla) -
        (0.828 * edad_anios),
      sexo == 2 ~ 8.608 + (0.291 * suma_pliegues) + (38.893 * indice_cintura_talla) - 
        (0.176 * edad_anios),
      TRUE ~ NA_real_
    ), 
    
    # Masa Grasa en Kg
    masa_grasa_kg_ict = (grasa_ict / 100) * peso_kg,
    
    # Estimación del %GC - Ecuación 2 de Urra et al. (2021)
    grasa_ip = case_when(
      sexo == 1 ~ 20.720 + (0.492 * suma_pliegues) + (0.354 * indice_ponderal) - 
        (0.923 * edad_anios),
      sexo == 2 ~ 16.087 + (0.306 * suma_pliegues) + (0.818 * indice_ponderal) - 
        (0.300 * edad_anios),
      TRUE ~ NA_real_
    ),
    
    # Masa Grasa en Kg
    masa_grasa_kg_ip = (grasa_ip / 100) * peso_kg,
    
    # WC ≥ 95th percentile for age and sex
    sexo_rec = if_else(sexo == 1, "male", "female"),
    
    wc_percentile = sds(
      perimetro_cintura,
      age = edad_anios,
      sex = sexo_rec, male = "male", female = "female",
      item = "wc_sharma",
      ref = us.ref,
      type = "perc"
    ), 
    
    p95_cintura = if_else(wc_percentile >= 0.95, 1, 0),
    
    # Z-Scores
    z_scores = anthroplus_zscores(
      sex = sexo,
      age_in_months = edad_meses,
      weight_in_kg = peso_kg,
      height_in_cm = talla_cm
    )
  ) |> 
  tidyr::unpack(z_scores) |>
  mutate(
    zbfa_dx = case_when(
      zbfa > 2 ~ "Obesidad",
      zbfa > 1 ~ "Sobrepeso",
      zbfa < -2 ~ "Delgadez",
      zbfa < -3 ~ "Delgadez Severa",
      TRUE      ~ "Normal"
    ),
    zhfa_dx = case_when(
      zhfa < -3 ~ "Talla baja severa",
      zhfa < -2 ~ "Talla baja (Stunting)",
      zhfa > 3  ~ "Talla muy alta (revisar)", 
      is.na(zhfa) ~ "Dato faltante",
      TRUE      ~ "Talla Normal"
    ),
    
    # Dinamometria
    dinamometria = pmax(dinamo_1, dinamo_2, dinamo_3, dinamo_max, na.rm = TRUE),
    
    # Presión arterial y frecuencia cardíaca
    PAS = rowMeans(across(
      c(
        pas_1,
        pas_2,
        pas_3
      )
    ), na.rm = TRUE),
    
    PAD = rowMeans(across(
      c(
        pad_1,
        pad_2,
        pad_3
      )
    ), na.rm = TRUE),
    
    pulso = rowMeans(across(
      c(
        pulso_1,
        pulso_2,
        pulso_3
      )
    ), na.rm = TRUE),

    sex_pedbp = if_else(sexo == 1, 1, 0))

# Pediatric Blood Pressure Distribution
bp_results <- p_bp(
  q_sbp = data_clear$PAS,
  q_dbp = data_clear$PAD,
  age   = data_clear$edad_meses,
  male  = data_clear$sex_pedbp,
  height = data_clear$talla_cm
)

data_clear <- data_clear |>
  mutate(
    
    # SBP and/or DBP ≥ 90th percentile for age, sex and height
    sbp_p = bp_results$sbp_p * 100,
    dbp_p = bp_results$dbp_p * 100,
    
    p90_bp = if_else(sbp_p >= 90 | dbp_p >= 90, 1, 0),
    crit_tg   = if_else(trigliceridos_mmol >= 1.24, 1, 0),
    crit_hdl  = if_else(hdl_mmol <= 1.03, 1, 0),
    crit_glucosa  = if_else(glucosa_mmol >= 5.6, 1, 0),
    
    # Sumamos los criterios presentes
    n_metabolic_abnormalities = rowSums(across(c(
      p95_cintura, crit_tg, crit_hdl, p90_bp, crit_glucosa)), na.rm = TRUE), 
    
    # Definimos salud metabólica
    metabolic_health = if_else(n_metabolic_abnormalities >= 2, "Metabólicamente no saludable", "Metabólicamente saludable"),
    
    # Depression
    across(
      sintomas_depresivos_1:sintomas_depresivos_9,
      ~ case_match(
        .x,
        "Nunca" ~ 0,
        "Varios días" ~ 1,
        "Más de la mitad de los días" ~ 2,
        "Casi todos los días" ~ 3
      )
    ),
    
    PHQ_9 = rowSums(across(sintomas_depresivos_1:sintomas_depresivos_9), na.rm = TRUE),
    
    depresion = case_when(
      PHQ_9 <= 4 ~ "Mínima",
      PHQ_9 >= 5 & PHQ_9 <= 9 ~ "Leve",
      PHQ_9 >= 10 & PHQ_9 <= 14 ~ "Moderada",
      PHQ_9 >= 15 & PHQ_9 <= 19 ~ "Moderadamente severa",
      PHQ_9 >= 20 ~ "Severa",
      TRUE ~ NA_character_) |>
      fct_relevel(
        "Mínima", "Leve", "Moderada", "Moderadamente severa", "Severa"),
    
    # Ansiedad
    across(
      sintomas_ansiedad_1:sintomas_ansiedad_10,
      ~ case_match(
        .x,
        "Nunca" ~ 0,
        "Ocasionalmente" ~ 1,
        "Mitad del tiempo" ~ 2,
        "La mayor parte del tiempo" ~ 3,
        "Todo el tiempo" ~ 4
      )
    ),
    
    GAD_7 = rowSums(across(sintomas_ansiedad_1:sintomas_ansiedad_10), na.rm = TRUE),
    
    ansiedad = case_when(
      GAD_7 <= 4 ~ "Mínima",
      GAD_7 >= 5 & GAD_7 <= 9 ~ "Leve",
      GAD_7 >= 10 & GAD_7 <= 14 ~ "Moderada",
      GAD_7 >= 15 ~ "Severa",
      TRUE ~ NA_character_) |>
      fct_relevel(
        "Mínima", "Leve", "Moderada", "Severa"),
  
    # Nutricion
    across(
      starts_with("nutricion") & 
        !all_of(c("nutricion_3", "nutricion_8", "nutricion_14", "nutricion_18", "nutricion_21")),
      ~ case_match(
        .x,
        "Verdadero" ~ 1,
        "Falso" ~ 0,
        "Nunca" ~ NA_real_,
        .default = NA_real_
      )
    ),
    across(
      all_of(c("nutricion_3", "nutricion_8", "nutricion_14", "nutricion_18", "nutricion_21")),
      ~ case_match(
        .x,
        "Verdadero" ~ 0,
        "Falso" ~ 1,
        "Nunca" ~ NA_real_,
        .default = NA_real_
      )
    ))

data_clear <- data_clear |>
  rowwise() |>
  mutate(
    
    # Contar cuántas respuestas saludables (1s) obtuvo el sujeto
    n_saludables = sum(c_across(starts_with("nutricion")), na.rm = TRUE),
    
    # Contar cuántas preguntas respondió (excluyendo NAs y "No aplicable")
    n_completados = sum(!is.na(c_across(starts_with("nutricion")))),
    
    # Aplicar la fórmula de ajuste del manual
    afhc_score = n_saludables * (23 / n_completados)) |>
  ungroup()

data_clear <- data_clear |>
  mutate(   
    
    categoria_afhc = if_else(afhc_score >= 11, "Saludable", "No saludable"),
    
    # PAQ-C
    across(
    c(paqc_1, paqc_2, paqc_3, paqc_4, paqc_5, paqc_6, paqc_7), ~ as.numeric(.x)),
    
    d1 = obtener_puntaje_dia(
      paqc_8_1_ninguna,
      paqc_8_1_a_veces,
      paqc_8_1_regular,
      paqc_8_1_frecuente,
      paqc_8_1_muy_frecuente
    ), 
    d2 = obtener_puntaje_dia(
      paqc_8_2_ninguna,
      paqc_8_2_a_veces,
      paqc_8_2_regular,
      paqc_8_2_frecuente,
      paqc_8_2_muy_frecuente
    ), 
    d3 = obtener_puntaje_dia(
      paqc_8_3_ninguna,
      paqc_8_3_a_veces,
      paqc_8_3_regular,
      paqc_8_3_frecuente,
      paqc_8_3_muy_frecuente
    ), 
    d4 = obtener_puntaje_dia(
      paqc_8_4_ninguna,
      paqc_8_4_a_veces,
      paqc_8_4_regular,
      paqc_8_4_frecuente,
      paqc_8_4_muy_frecuente
    ), 
    d5 = obtener_puntaje_dia(
      paqc_8_5_ninguna,
      paqc_8_5_a_veces,
      paqc_8_5_regular,
      paqc_8_5_frecuente,
      paqc_8_5_muy_frecuente
    ), 
    d6 = obtener_puntaje_dia(
      paqc_8_6_ninguna,
      paqc_8_6_a_veces,
      paqc_8_6_regular,
      paqc_8_6_frecuente,
      paqc_8_6_muy_frecuente
    ), 
    d7 = obtener_puntaje_dia(
      paqc_8_7_ninguna,
      paqc_8_7_a_veces,
      paqc_8_7_regular,
      paqc_8_7_frecuente,
      paqc_8_7_muy_frecuente
    ), 
    
    paq_item9_score = rowMeans(across(c(d1, d2, d3, d4, d5, d6, d7)), na.rm = TRUE),
    
    paqc_final_score = rowMeans(across(c(
      paqc_1, paqc_2, paqc_3, paqc_4, paqc_5, paqc_6, paqc_7, paq_item9_score
    )), na.rm = TRUE),
    
    paqc_dx = case_when(
      paqc_final_score <= 1 ~ "Muy sedentario",
      paqc_final_score >= 2 & paqc_final_score <= 3 ~ "Moderadamente activo",
      paqc_final_score >= 4 & paqc_final_score <= 5 ~ "Muy activo"),
    
    # FVC
    fvc_maximo = pmax(
      fvc, fvc_2, fvc_3, fvc_4, fvc_5, fvc_6, fvc_7, fvc_8, na.rm = TRUE),
    
    # FEV1
    fev1_maximo = pmax(
      fev1, fev1_2, fev1_3, fev1_4, fev1_5, fev1_6, fev1_7, fev1_8, na.rm = TRUE),
    
    # PEF
    pef_maximo = pmax(
      pef, pef_2, pef_3, pef_4, pef_5, pef_6, pef_7, pef_8, na.rm = TRUE),
    
    # FEV3
    fev3_maximo = pmax(
      fev3, fev3_2, fev3_3, fev3_4, fev3_5, fev3_6, fev3_7, fev3_8, na.rm = TRUE),
    
    # FEV6
    fev6_maximo = pmax(
      fev6, fev6_2, fev6_3, fev6_4, fev6_5, fev6_6, fev6_7, fev6_8, na.rm = TRUE),
    
    # Calcular el índice FEV1/FVC
    fev1_fvc_ratio = (fev1_maximo / fvc_maximo) * 100,
    
    interpretacion_espiro = case_when(
      fev1_fvc_ratio < 80 ~ "Posible Obstrucción",
      fev1_fvc_ratio >= 80 & fvc_maximo < 80 ~ "Posible Restricción",
      fev1_fvc_ratio >= 80 ~ "Normal",
      TRUE ~ NA_character_
    ),

    # Ajustamos el sexo para rspiro (1=M, 2=F)
    sex_rspiro = if_else(sexo == 1, 1, 2), 
    
    z_fev1 = zscore_GLI(
      age = edad_anios,
      height = talla_m,
      gender = sex_rspiro,
      ethnicity = 5,
      FEV1 = fev1_maximo
    ), 
    
    z_fvc  = zscore_GLI(
      age = edad_anios,
      height = talla_m,
      gender = sex_rspiro,
      ethnicity = 5,
      FVC = fvc_maximo
    ), 
    
    z_fev1_fvc  = zscore_GLI(
      age = edad_anios,
      height = talla_m,
      gender = sex_rspiro,
      ethnicity = 5,
      FEV1FVC = fev1_fvc_ratio
    ), 

    # Conversión de Z-score a Percentil (0-100)
    fev1_p = pnorm(z_fev1) * 100,
    fvc_p  = pnorm(z_fvc) * 100,
    fev1_fvc_p  = pnorm(z_fev1_fvc) * 100,

    # Cálculo del % del Predicho (Opcional, muy usado en clínica)
    # La función pctgli da el valor: (Medido / Predicho) * 100
    fev1_pct_pred = pctpred_GLI(
      age = edad_anios,
      height = talla_m,
      gender = sex_rspiro,
      ethnicity = 5,
      FEV1 = fev1_maximo
    ), 
    
    # Criterio: ¿Está por debajo del percentil 5? (Límite Inferior de Normalidad)
    crit_lung_fev1_p = if_else(fev1_p <= 5, 1, 0),
    crit_lung_fvc_p = if_else(fvc_p <= 5, 1, 0),
    crit_lung_fev1_fvc_p = if_else(fev1_fvc_p <= 5, 1, 0),
    
    clasificacion_espiro = case_when(
      fev1_fvc_p <= 5 ~ "Sugerente de Obstrucción",
      fvc_p <= 5 ~ "Sugerente de Restricción",
      TRUE ~ NA
    ), 
    
    # Cluster de PM2.5
    cluster = case_match(
      colegio_id, 
      c("Colegio Jorge Basadre - VMT", "Colegio Santísima Virgen de Chapi - Pachacamac") ~
        "Cluster 1",
      "Colegio 0028 Jesus y María - La Molina" ~ "Cluster 2")
  )
```

```{r}
tbl_1 <- data_clear |>
  dplyr::select(22:41)

edad_pariente

table(tbl_1$pariente_del_infante)

lapply(tbl_1, function(x) table(x))
```


## Tabla 1. Biomarcadores

```{r}
tbl_1 <- data_clear |>
  dplyr::select(
    glucosa, trigliceridos, hdl_colesterol, colesterol_total, PAS, PAD, pulso, cluster) |>
  tbl_summary(
    by = cluster,
    digits = list(all_continuous() ~ c(2, 2)),
    label = list(
      glucosa ~ "Glucosa en ayunas (mg/dL)",
      trigliceridos ~ "Triglicéridos (mg/dL)",
      hdl_colesterol ~ "HDL-c (mg/dL)",
      colesterol_total ~ "Colesterol total (mg/dL)",
      PAS ~ "Presión arterial sistólica (mmHg)",
      PAD ~ "Presión arterial diastólica (mmHg)",
      pulso ~ "Frecuencia cardíaca (latidos por minuto)"
      ),
    missing = "no") |>
  add_overall() |>
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 3)) |>
  bold_labels() |>
  bold_p(t = 0.05) |> 
  modify_header(
    label = "**Caraterísticas**",
    stat_0 = "**Total** (n = {n})",
    stat_1 = "**Cluster 1** (n = {n})",
    stat_2 = "**Cluster 2** (n = {n})") |>
  modify_caption(caption = "**Tabla 1. Biomarcadores** N = {N}")

tbl_1
```

## Tabla 2. Antropometría

```{r}
tbl_2 <- data_clear |>
  dplyr::select(
    sexo_factor, edad_anios, peso_kg, talla_m, peso_kg, imc, 
    pliegue_bicipital, pliegue_tricipital, pliegue_subescapular, perimetro_cuello,
    cluster) |>
  tbl_summary(
    by = cluster,
    digits = list(all_continuous() ~ c(2, 2), all_categorical() ~ c(1, 1)),
    statistic = list(all_categorical() ~"{n} ({p}%)"),
    label = list(
      sexo_factor	~ "Sexo",
      edad_anios ~ "Edad (años)",
      peso_kg ~ "Peso (Kg)",
      talla_m	~ "Talla (metros)",
      imc ~ "IMC",
      pliegue_bicipital	~ "Pliegue bicipital (mm)",
      pliegue_tricipital ~ "Pliegue tricipital (mm)",
      pliegue_subescapular ~ "Pliegue subescapular (mm)",
      perimetro_cuello ~ "Perímetro del cuello (cm)"
      ), 
    missing = "no") |>
  add_overall() |>
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 3)) |>
  bold_labels() |>
  bold_p(t = 0.05) |>
  modify_header(
    label = "**Caraterísticas**",
    stat_0 = "**Total** (n = {n})",
    stat_1 = "**Cluster 1** (n = {n})",
    stat_2 = "**Cluster 2** (n = {n})") |>
  modify_caption(caption = "**Tabla 2. Antropometría** N = {N}")

tbl_2
```

## Tabla 3. Grasa corporal

```{r}
tbl_3 <- data_clear |>
  dplyr::select(
    perimetro_cintura, perimetro_cadera, indice_cintura_cadera, grasa_boileau, 
    grasa_slaughet, grasa_deurenberg, grasa_ict, grasa_ip, zbfa_dx, zhfa_dx, 
    dinamometria, cluster, imc) |>
  tbl_summary(
    by = cluster,
    digits = list(all_continuous() ~ c(2, 2), all_categorical() ~ c(1, 1)),
    statistic = list(all_categorical() ~"{n} ({p}%)"),
    label = list(
      perimetro_cintura	~ "Perímetro de cintura (cm)",
      perimetro_cadera	~ "Perímetro de cadera (cm)",
      indice_cintura_cadera	~ "ICC",
      grasa_boileau ~ "%GC Boileau et al. (1985)",
      grasa_slaughet ~ "%GC Slaughetr et al. (1988)",
      grasa_deurenberg ~ "%GC Deuremberg et al.(1991)",
      grasa_ict ~ "%GC índice cintura talla",
      grasa_ip ~ "%GC índice ponderal",
      zbfa_dx ~ "IMC para la edad",
      zhfa_dx ~ "Talla para la edad",
      dinamometria ~ "Dinamometría"
      ),
    missing = "no") |>
  add_overall() |>
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 3)) |>
  bold_labels() |>
  bold_p(t = 0.05) |>
  modify_header(
    label = "**Caraterísticas**",
    stat_0 = "**Total** (n = {n})",
    stat_1 = "**Cluster 1** (n = {n})",
    stat_2 = "**Cluster 2** (n = {n})") |>
  modify_caption(caption = "**Tabla 3. Grasa corporal** N = {N}")

tbl_3
```

##

```{r}
tbl_4 <- data_clear |>
  dplyr::select(
    estado_civil_pariente, estad_civil_pariente, nivel_educativo_pariente,
    situacion_laboral_pariente, laboral_pariente_1, sit_economica_1, sit_economica_2,
    sit_economica_3, seguro_de_salud_adolescente, lactancia_materna, cluster) |>
  tbl_summary(
    by = cluster,
    digits = list(all_continuous() ~ c(2, 2), all_categorical() ~ c(1, 1)),
    statistic = list(all_categorical() ~"{n} ({p}%)"),
    # label = list(
    #   perimetro_cintura	~ "Perímetro de cintura (cm)",
    #   perimetro_cadera	~ "Perímetro de cadera (cm)",
    #   indice_cintura_cadera	~ "ICC",
    #   grasa_boileau ~ "%GC Boileau et al. (1985)",
    #   grasa_slaughet ~ "%GC Slaughetr et al. (1988)",
    #   grasa_deurenberg ~ "%GC Deuremberg et al.(1991)",
    #   grasa_ict ~ "%GC índice cintura talla",
    #   grasa_ip ~ "%GC índice ponderal",
    #   zbfa_dx ~ "IMC para la edad",
    #   zhfa_dx ~ "Talla para la edad",
    #   dinamometria ~ "Dinamometría"),
    missing = "no") |>
  add_overall() |>
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 3)) |>
  bold_labels() |>
  bold_p(t = 0.05) |>
  modify_header(
    label = "**Caraterísticas**",
    stat_0 = "**Total** (n = {n})",
    stat_1 = "**Cluster 1** (n = {n})",
    stat_2 = "**Cluster 2** (n = {n})") |>
  modify_caption(caption = "**Tabla 3. Grasa corporal** N = {N}")

tbl_4
```

```{r}
tbl_1_data <- data_clear |>
  dplyr::select(alergia_pteronyssinus:severidad_rinitis, feno, cluster) |>
  tbl_summary(
    by = cluster,
    digits = list(all_continuous() ~ c(2, 2)),
    missing = "always") |>
  add_overall() |>
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 3)) |>
  bold_labels() |>
  bold_p(t = 0.05)

tbl_1_data
```

```{r}
tbl_1_data <- data_clear |>
  dplyr::select(sintomas_respiratorios_acaros_del_polvo_polvo_casero:feno, cluster) |>
  tbl_summary(
    by = cluster,
    digits = list(all_continuous() ~ c(2, 2)),
    missing = "always") |>
  add_overall() |>
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 3)) |>
  bold_labels() |>
  bold_p(t = 0.05)

tbl_1_data
```

```{r}
tbl_1_data <- data_clear |>
  dplyr::select(PHQ_9:paqc_dx, 
                cluster) |>
  tbl_summary(
    by = cluster,
    digits = list(all_continuous() ~ c(2, 2)),
    missing = "always") |>
  add_overall() |>
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 3)) |>
  bold_labels() |>
  bold_p(t = 0.05)

tbl_1_data

# Limpiar tablas
# Calculo del tamaño de muestra basada en conglomerados, para que la unidad de analisis sean colegios y no niños
```

