library(labelled)

var_label(data$record_id) <- "Record ID"
var_label(data$redcap_event_name) <- "Event Name"
var_label(data$redcap_repeat_instrument) <- "Repeat Instrument"
var_label(data$redcap_repeat_instance) <- "Repeat Instance"
var_label(data$colegio_id) <- "¿A qué colegio pertenece?"
var_label(data$numero_visita) <- "Número de visita"
var_label(data$consentimiento_1) <- "¿El padre, madre o tutor legal firmó el consentimiento informado para autorizar la participación del menor en este estudio?"
var_label(data$consentimiento_2) <- "¿El padre, madre o tutor legal firmó el consentimiento informado para participar en este estudio?"
var_label(data$consentimiento_nombre) <- "Nombre de la persona que firmó el consentimiento informado"
var_label(data$consenti_relacion) <- "Relación con el niño/adolescente"
var_label(data$consenti_relacion_otro) <- "Otro (especifique):"
var_label(data$asentimiento_1) <- "¿El niño/adolescente recibió la hoja de asentimiento en un lenguaje adecuado para su edad?"
var_label(data$asentimiento_2) <- "¿El niño/adolescente expresó libremente su deseo de participar en el estudio (asentimiento informado)?"
var_label(data$asentimiento_nombre) <- "Nombre de la persona que firmó el consentimiento informado"
var_label(data$consent_asent_investig) <- "El encuestador/investigador verificó la firma del consentimiento y asentimiento."
var_label(data$encuestador_0) <- "Encuestador"
var_label(data$fecha_hora_0) <- "Fecha y hora (fin)"
var_label(data$comentario_0) <- "Comentario adicional"
var_label(data$cuestionario_adolescentes_0_consent_asent_complete) <- "Complete?"
var_label(data$pariente_del_infante) <- "¿Quién completa el formulario?"
var_label(data$pariente_del_infante_2) <- "Otro pariente (especifique):"
var_label(data$nombre_apoderado) <- "Nombre y Apellidos del familiar (madre/padre/apoderado)"
var_label(data$fecha_nacimiento_pariente) <- "Fecha de nacimiento de la madre/padre/pariente:"
var_label(data$edad_pariente) <- "Edad autorreportada de la madre/padre/pariente"
var_label(data$celular_pariente) <- "Celular de la madre/padre/apoderado"
var_label(data$estado_civil_pariente) <- "¿Cuál es su estado civil?"
var_label(data$estad_civil_pariente) <- "Actualmente usted: "
var_label(data$nivel_educativo_pariente) <- "¿Cuál es su nivel educativo?Del padre/madre/apoderado que está llenando la encuesta"
var_label(data$situacion_laboral_pariente) <- "¿Cuál es su situación laboral actual?"
var_label(data$laboral_pariente_1) <- "Otra, especifique: "
var_label(data$sit_economica_1) <- "¿Cómo describiría la situación económica actual de su familia?"
var_label(data$sit_economica_2) <- "En comparación con hace cinco años, ¿cómo considera que está la situación económica de su familia ahora?"
var_label(data$sit_economica_3) <- "En comparación con hace cinco años, ¿cómo considera que está la situación económica de su familia ahora?"
var_label(data$seguro_de_salud_adolescente) <- "¿Qué tipo de seguro de salud tiene el adolescente?"
var_label(data$direccion_distrito) <- "¿En qué dirección y distrito vive actualmente? Es necesario poner la dirección exacta"
var_label(data$ano_residencia) <- "¿Hace cuánto tiempo vive en este domicilio en años?"
var_label(data$nombre_hijo) <- "Nombre y Apellidos del niño que será evaluado"
var_label(data$orden_del_hijo) <- "¿Qué orden ocupa el niño(a) participante (su hijo) entre sus hijos(as)?"
var_label(data$fecgha_nacimiento_adolescente) <- "Fecha de nacimiento del el participante (su hijo) "
var_label(data$edad_adolescente) <- "Edad adolescente (autorreportada por el padre)"
var_label(data$lactancia_materna) <- "Con respecto a la lactancia materna, el participante (su hijo):¿Recibió leche materna exclusiva hasta los 6 meses de edad ?"
var_label(data$lactancia_materna_2) <- "¿Qué edad tenía su hijo cuando dejó de recibir leche materna por completo? "
var_label(data$lactancia_materna_2_meses) <- "Indicar en meses"
var_label(data$lactancia_materna_3) <- "¿A qué edad comenzó a tomar leche de fórmula?"
var_label(data$lactancia_materna_3_meses) <- "Indicar en meses"
var_label(data$lactancia_materna_4) <- "¿A qué edad comenzó la alimentación complementaria (por ejemplo, papillas)? "
var_label(data$lactancia_materna_4_meses) <- "Indicar meses"
var_label(data$hospitalizado_nino_nacer) <- "Durante el primer año de nacido, ¿el adolescente (su hijo) fue hospitalizado al nacer?"
var_label(data$hospitalizado_nino_nacer_1) <- "Si marcó Sí, indique la duración de la hospitalización:"
var_label(data$enf_bajopeso_prematuro) <- "¿El adolescente nació con bajo peso o de forma prematura (antes de las 37 semanas de gestación)?"
var_label(data$enf_macrosomia) <- "¿El adolescente nació con macrosomía (peso mayor de 4 kilos al nacer)?"
var_label(data$enf_pulmonares_rinitis_alergica) <- "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice<-Rinitis alérgica)"
var_label(data$enf_pulmonares_asma) <- "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice<-Asma)"
var_label(data$enf_pulmonares_dermatitis_atopica) <- "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice<-Dermatitis atópica)"
var_label(data$enf_pulmonares_bronquitis_cronica) <- "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice<-Bronquitis crónica)"
var_label(data$enf_pulmonares_ninguna) <- "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice<-Ninguna)"
var_label(data$enf_pulmonares_unknown) <- "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice<-Unknown)"
var_label(data$enf_pulmonares_no_information) <- "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice<-No information)"
var_label(data$enf_pulmonares_invalid) <- "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice<-Invalid)"
var_label(data$enf_pulmonares_not_asked) <- "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice<-Not asked)"
var_label(data$enf_dm1) <- "¿El adolescente ha sido diagnosticado con diabetes tipo 1?"
var_label(data$enf_resit_insulina) <- "¿El adolescente ha presentado resistencia a la insulina?"
var_label(data$enf_dislipidemias) <- "¿El adolescente  ha sido diagnosticado con dislipidemia (colesterol o triglicéridos elevados o ambas)?"
var_label(data$inf_respirat_recurrentes) <- "¿El adolescente  ha tenido infecciones respiratorias recurrentes (es decir, neumonía, gripe)?"
var_label(data$enf_medicamentos_cronicos) <- "¿El adolescente ha usado medicamentos de forma crónica (por más de 3 meses)?"
var_label(data$enf_medicamentos_cronicos_si) <- "Si marcó Sí, indique qué medicamentos usa o ha usado: "
var_label(data$hospita_previas) <- "Durante este año, ¿El adolescente ha tenido hospitalizaciones previas?"
var_label(data$hospita_previas_1) <- "Si marcó Sí, ¿Cuántas veces fue hospitalizado?"
var_label(data$hospita_previas_2) <- "Si marcó Sí, ¿Por qué motivos fue hospitalizado? "
var_label(data$vacunas) <- "Durante este año, ¿el adolescente tiene sus vacunas al día?"
var_label(data$vacunas_2) <- "Si marcó Sí,  ¿Qué vacunas tiene actualmente?"
var_label(data$ant_familiar_pulmon) <- "¿Algún familiar tiene diagnóstico de asma, rinitis o enfermedad pulmonar obstructiva crónica (EPOC)?"
var_label(data$ant_familiar_pulmon_2) <- "Si marcó Sí, indiquie quién(es): "
var_label(data$ant_diabetes2) <- "¿Algún familiar ha sido diagnosticado con diabetes tipo 2?"
var_label(data$ant_diabetes2_2) <- "Si marcó Sí, indiquie quién(es): "
var_label(data$ant_hta) <- "¿Algún familiar ha sido diagnosticado con hipertensión arterial?"
var_label(data$ant_hta_2) <- "Si marcó Sí, indiquie quién(es): "
var_label(data$ant_fenf_cardiov) <- "¿Algún familiar ha tenido enfermedad cardiovascular precoz (por ejemplo, infarto agudo de miocardio o accidente cerebrovascular antes de los 55 años en varones o 65 años en mujeres)?"
var_label(data$ant_fenf_cardiov_2) <- "Si marcó Sí, indiquie quién(es): "
var_label(data$ant_dislipidemias) <- "¿Algún familiar ha sido diagnosticado con dislipidemia (hipercolesterolemia, hipertrigliceridemia o ambas)?"
var_label(data$ant_dislipidemias_2) <- "Si marcó Sí, indiquie quién(es): "
var_label(data$ant_cancer) <- "¿Algún familiar ha tenido cáncer?"
var_label(data$ant_cancer_2) <- "Si marcó Sí, indiquie quién(es): "
var_label(data$ant_obesidad) <- "¿Algún familiar tiene obesidad o sobrepeso?"
var_label(data$ant_obesidad_2) <- "Si marcó Sí, indiquie quién(es): "
var_label(data$ant_familiar_otros) <- "¿Algún familiar tiene otras enfermedades (especifique)?"
var_label(data$ant_familiar_otros_2) <- "Si marcó Sí, indiquie quién(es): "
var_label(data$ansiedad_1) <- "A. Ansiedad¿Con qué frecuencia se sintió nervioso(a), intranquilo(a) o con los nervios de punta?"
var_label(data$ansiedad_2) <- "¿Con qué frecuencia sintió que no podía dejar de preocuparse o controlar la preocupación?"
var_label(data$depresion_1) <- "B. Depresión:¿Con qué frecuencia tuvo poco interés o placer en hacer cosas?"
var_label(data$depresion_2) <- "¿Con qué frecuencia se ha sentido decaído(a), deprimido(a) o sin esperanzas? "
var_label(data$cond_agresiv_1) <- "A. Conductas dentro del hogar:¿Con qué frecuencia su hijo/a gritó a otros niños en casa?"
var_label(data$cond_agresiv_2) <- "¿Con qué frecuencia su hijo(a) gritó a adultos en casa (por ejemplo, padres, cuidadores u otros familiares)?"
var_label(data$cond_agresiv_3) <- "¿Con qué frecuencia su hijo(a) insultó a otros niños en casa?"
var_label(data$cond_agresiv_4) <- "¿Con qué frecuencia su hijo(a) insultó a adultos en casa?"
var_label(data$cond_agresiv_5) <- "¿Con qué frecuencia su hijo(a) amenazó verbalmente con golpear a un niño en casa?"
var_label(data$cond_agresiv_6) <- "B. Conductas fuera del hogar:¿Con qué frecuencia su hijo(a) gritó a amigos o compañeros fuera de casa?"
var_label(data$cond_agresiv_7) <- "¿Con qué frecuencia su hijo(a) gritó a adultos fuera de casa (por ejemplo, profesores, vecinos u otros adultos)?"
var_label(data$cond_agresiv_8) <- "¿Con qué frecuencia su hijo(a) insultó a amigos o compañeros fuera de casa?"
var_label(data$cond_agresiv_9) <- "¿Con qué frecuencia su hijo(a) insultó a adultos fuera de casa?"
var_label(data$encuestador_8) <- "Encuestador"
var_label(data$fecha_hora_8) <- "Fecha y hora (fin)"
var_label(data$comentario_antropometria_5) <- "Comentario adicional"
var_label(data$cuestionario_padres_sociodemografico_complete) <- "Complete?"
var_label(data$exposoma_1_1a) <- "Duración (minutos) - a pie (caminando)"
var_label(data$exposoma_1_1b) <- "Número de días en la semana - a pie (caminando)"
var_label(data$exposoma_1_2a) <- "Duración (minutos) - en bicicleta"
var_label(data$exposoma_1_2b) <- "Número de días en la semana - en bicicleta"
var_label(data$exposoma_1_3a) <- "Duración (minutos) - en bus o en combi o metropolitano "
var_label(data$exposoma_1_3b) <- "Número de días en la semana - en bus o en combi o metropolitano "
var_label(data$exposoma_1_4a) <- "Duración (minutos) - en metro o tren"
var_label(data$exposoma_1_4b) <- "Número de días en la semana - en metro o tren "
var_label(data$exposoma_1_5a) <- "Duración (minutos) - en carro (auto propio, movilidad escolar, taxi o colectivo)"
var_label(data$exposoma_1_5b) <- "Número de días en la semana - en carro (auto propio, movilidad escolar, taxi o colectivo) "
var_label(data$exposoma_1_6a) <- "Duración (minutos) - en moto taxi o moto lineal"
var_label(data$exposoma_1_6b) <- "Número de días en la semana - en moto taxi o moto lineal"
var_label(data$exposoma_2_1a) <- "Duración (minutos) - a pie (caminando)"
var_label(data$exposoma_2_1b) <- "Número de días en la semana - a pie (caminando)"
var_label(data$exposoma_2_2a) <- "Duración (minutos) - en bicicleta"
var_label(data$exposoma_2_2b) <- "Número de días en la semana - en bicicleta"
var_label(data$exposoma_2_3a) <- "Duración (minutos) - en bus o en combi o metropolitano "
var_label(data$exposoma_2_3b) <- "Número de días en la semana - en bus o en combi o metropolitano "
var_label(data$exposoma_2_4a) <- "Duración (minutos) - en metro o tren"
var_label(data$exposoma_2_4b) <- "Número de días en la semana - en metro o tren "
var_label(data$exposoma_2_5a) <- "Duración (minutos) - en carro (auto propio, movilidad escolar, taxi o colectivo)"
var_label(data$exposoma_2_5b) <- "Número de días en la semana - en carro (auto propio, movilidad escolar, taxi o colectivo) "
var_label(data$exposoma_2_6a) <- "Duración (minutos) - en moto taxi o moto lineal"
var_label(data$exposoma_2_6b) <- "Número de días en la semana - en moto taxi o moto lineal"
var_label(data$exposoma_3) <- "Ayer, además del colegio o de su casa, ¿su hijo fue a algún otro lugar?(Por ejemplo: casa de un amigo o familiar, parque, centro comercial, mercado, iglesia, entrenamiento deportivo, etc.)."
var_label(data$exposoma_3_lugares_lugar_1) <- "Cuántos lugares (1, 2, 3) marcó el familiares (choice<-Lugar 1)"
var_label(data$exposoma_3_lugares_lugar_2) <- "Cuántos lugares (1, 2, 3) marcó el familiares (choice<-Lugar 2)"
var_label(data$exposoma_3_lugares_lugar_3) <- "Cuántos lugares (1, 2, 3) marcó el familiares (choice<-Lugar 3)"
var_label(data$exposoma_3_lugares_unknown) <- "Cuántos lugares (1, 2, 3) marcó el familiares (choice<-Unknown)"
var_label(data$exposoma_3_lugares_no_information) <- "Cuántos lugares (1, 2, 3) marcó el familiares (choice<-No information)"
var_label(data$exposoma_3_lugares_invalid) <- "Cuántos lugares (1, 2, 3) marcó el familiares (choice<-Invalid)"
var_label(data$exposoma_3_lugares_not_asked) <- "Cuántos lugares (1, 2, 3) marcó el familiares (choice<-Not asked)"
var_label(data$exposoma_3_lugar1_a) <- "Nombre o tipo de lugar"
var_label(data$exposoma_3_lugar1_b) <- "Nombre o tipo de lugar"
var_label(data$exposoma_3_lugar1_c) <- "Distrito"
var_label(data$exposoma_3_lugar1_d) <- "Modo de transporte (caminando, bus, combi, bicicleta, taxi) "
var_label(data$exposoma_3_lugar1_e) <- "Tiempo total de viaje (ida y vuelta) "
var_label(data$exposoma_3_lugar2_a) <- "Nombre o tipo de lugar"
var_label(data$exposoma_3_lugar2_b) <- "Nombre o tipo de lugar"
var_label(data$exposoma_3_lugar2_c) <- "Distrito"
var_label(data$exposoma_3_lugar2_d) <- "Modo de transporte (caminando, bus, combi, bicicleta, taxi) "
var_label(data$exposoma_3_lugar2_e) <- "Tiempo total de viaje (ida y vuelta) "
var_label(data$exposoma_3_lugar3_a) <- "Nombre o tipo de lugar"
var_label(data$exposoma_3_lugar3_b) <- "Nombre o tipo de lugar"
var_label(data$exposoma_3_lugar3_c) <- "Distrito"
var_label(data$exposoma_3_lugar3_d) <- "Modo de transporte (caminando, bus, combi, bicicleta, taxi) "
var_label(data$exposoma_3_lugar3_e) <- "Tiempo total de viaje (ida y vuelta) "
var_label(data$exposoma_4) <- "Durante el último mes, en promedio cuántas veces por semana (durante la semana)¿Cuántas veces jugó su hijo en espacios verdes?"
var_label(data$exposoma_5) <- "Durante el último mes, en promedio cuántas veces por semana (durante el fin de semana)¿Cuántas veces jugó su hijo en espacios verdes?"
var_label(data$exposoma_6) <- "Durante el último mes, en promedio cuántas horas por cada vez (durante la semana)¿Cuántas horas jugó su hijo en espacios verdes?"
var_label(data$exposoma_7) <- "Durante el último mes, en promedio cuántas horas por cada vez (durante el fin de semana)¿Cuántas horas jugó su hijo en espacios verdes?"
var_label(data$exposoma_8) <- "En el tiempo libre de su hijo/cuando no está en la escuela, ¿cuántas veces jugó su hijo en los espacios verdes hoy/ayer?"
var_label(data$exposoma_9) <- "En el tiempo libre de su hijo/cuando no está en la escuela, ¿cuántas veces jugó su hijo en los espacios verdes en la última semana?"
var_label(data$exposoma_10) <- "En el tiempo libre de su hijo/cuando no está en la escuela, ¿cuántas horas por cada vez jugó su hijo en los espacios verdes hoy/ayer?"
var_label(data$exposoma_11) <- "En el tiempo libre de su hijo/cuando no está en la escuela, ¿cuántas horas por cada vez jugó su hijo en los espacios verdes en la última semana?"
var_label(data$exposoma_12_escuela_ref1) <- "Nombre o referencia (año escolar, cuando hay clases)"
var_label(data$exposoma_12_escuela_ref2) <- "Nombre o referencia (año escolar, cuando hay clases)"
var_label(data$exposoma_12_escuela_ref3) <- "Nombre o referencia (año escolar, cuando hay clases)"
var_label(data$exposoma_12_escuela_dist1) <- "Nombre o referencia (año escolar, cuando hay clases)"
var_label(data$exposoma_12_escuela_dist2) <- "Nombre o referencia (año escolar, cuando hay clases)"
var_label(data$exposoma_12_escuela_dist3) <- "Nombre o referencia (año escolar, cuando hay clases)"
var_label(data$exposoma_12_vacas_ref1) <- "Nombre o referencia (año escolar, cuando hay clases)"
var_label(data$exposoma_12_vacas_ref2) <- "Nombre o referencia (año escolar, cuando hay clases)"
var_label(data$exposoma_12_vacas_dist1) <- "Nombre o referencia (año escolar, cuando hay clases)"
var_label(data$exposoma_12_vacas_dist2) <- "Nombre o referencia (año escolar, cuando hay clases)"
var_label(data$exposoma_12_vacas_dist3) <- "Nombre o referencia (año escolar, cuando hay clases)"
var_label(data$exposoma_13_1) <- "Durante el año escolar: Bosque, montaña o río "
var_label(data$exposoma_13_2) <- "Durante el año escolar: Playa"
var_label(data$exposoma_13_3) <- "Durante las vacaciones: Bosque, montaña o río "
var_label(data$exposoma_13_4) <- "Durante las vacaciones: Playa"
var_label(data$exposoma_13_5) <- "Durante la última semana: Bosque, montaña o río "
var_label(data$exposoma_13_6) <- "Durante la última semana: Playa"
var_label(data$exposoma_14_en_un_parque_o_area_verde_jardin_cerca_de_su_cas) <- "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice<-En un parque o área verde (jardín) cerca de su casa o barrio)"
var_label(data$exposoma_14_bosque_o_area_natural) <- "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice<-Bosque o área natural)"
var_label(data$exposoma_14_playa) <- "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice<-Playa)"
var_label(data$exposoma_14_patio_o_jardin_de_su_casa) <- "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice<-Patio o jardín de su casa)"
var_label(data$exposoma_14_en_otro_lugar) <- "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice<-En otro lugar)"
var_label(data$exposoma_14_unknown) <- "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice<-Unknown)"
var_label(data$exposoma_14_no_information) <- "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice<-No information)"
var_label(data$exposoma_14_invalid) <- "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice<-Invalid)"
var_label(data$exposoma_14_not_asked) <- "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice<-Not asked)"
var_label(data$exposoma_14_otro) <- " En otro lugar (especifique): "
var_label(data$espacio_verde_seguro) <- "En general, ¿cree que los espacios verdes cercanos a su casa  son seguros y adecuados para que los adolescentes jueguen?"
var_label(data$exposoma_15_1) <- "Este barrio es un lugar en el que disfruto vivir"
var_label(data$exposoma_15_2) <- "Es fácil obtener ayuda práctica de los vecinos"
var_label(data$exposoma_15_3) <- "En mi barrio se puede confiar en la mayoría de las personas"
var_label(data$exposoma_16) <- "¿Cuál de las siguientes opciones describe mejor su consumo de tabaco? (Responda usted, madre/padre/apoderado del adolescente)"
var_label(data$exposoma_17) <- "¿Alguien fuma actualmente dentro de su casa?"
var_label(data$exposoma_17_1) <- "¿Quién fuma dentro de su casa?"
var_label(data$exposoma_17_1_usted) <- "Usted, ¿Cuántos cigarrillos fuma por semana en total?"
var_label(data$exposoma_17_1_usted1) <- "Usted, ¿Cuántos de esos cigarrillos fuma dentro de la casa?"
var_label(data$exposoma_17_1_pareja) <- "Su pareja, ¿Cuántos cigarrillos fuma por semana en total?"
var_label(data$exposoma_17_1_pareja1) <- "Su pareja, ¿Cuántos de esos cigarrillos fuma dentro de la casa?"
var_label(data$exposoma_17_1_otra) <- "Otra persona del hogar (por ejemplo, abuelo, tío, hermano), ¿Cuántos cigarrillos fuma por semana en total?"
var_label(data$exposoma_17_1_otra1) <- "Otra persona del hogar (por ejemplo, abuelo, tío, hermano), ¿Cuántos de esos cigarrillos fuma dentro de la casa?"
var_label(data$exposoma_18) <- "Durante la última semana, ¿su hijo estuvo en algún lugar cerrado donde alguien estaba fumando?"
var_label(data$exposoma_18_1) <- "Si marcó sí, ¿cuántas veces por semana?"
var_label(data$exposoma_19) <- "Presencia de industrias o empresas cercanas ¿Cerca de su casa (a menos de 100 metros) hay alguna empresa, taller o industria que emita humo, gases, polvo u olores fuertes? "
var_label(data$exposoma_20_fabrica_o_planta_industrial_ejemplo_cemento_alim) <- "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice<-Fábrica o planta industrial (ejemplo: cemento, alimentos, textiles, etc.))"
var_label(data$exposoma_20_taller_mecanico_o_de_soldadura) <- "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice<-Taller mecánico o de soldadura)"
var_label(data$exposoma_20_panaderia_o_polleria) <- "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice<-Panadería o polleria)"
var_label(data$exposoma_20_empresa_de_transporte_o_estacion_de_buses_camion) <- "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice<-Empresa de transporte o estación de buses/camiones)"
var_label(data$exposoma_20_otra_exposoma_20_otro) <- "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice<-Otra {exposoma_20_otro})"
var_label(data$exposoma_20_unknown) <- "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice<-Unknown)"
var_label(data$exposoma_20_no_information) <- "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice<-No information)"
var_label(data$exposoma_20_invalid) <- "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice<-Invalid)"
var_label(data$exposoma_20_not_asked) <- "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice<-Not asked)"
var_label(data$exposoma_20_otro) <- "Especifique:"
var_label(data$exposoma_21) <- "Aproximadamente, ¿A qué distancia se encuentra la empresa más cercana?"
var_label(data$exposoma_22) <- "ii. Emisiones visibles ¿Ha visto usted que esta empresa o industria emite humo, polvo o gases hacia el aire? "
var_label(data$exposoma_23) <- "¿Con qué frecuencia observa estas emisiones durante la semana?"
var_label(data$exposoma_24) <- "¿A qué hora del día suele empezar la emisión de humo, gases o polvo? "
var_label(data$exposoma_25) <- "¿Hasta qué hora aproximadamente continúan las emisiones?"
var_label(data$exposoma_26) <- "iii. Características del humo o polvo Cuando ve el humo o el polvo, ¿de qué color suele ser principalmente? "
var_label(data$exposoma_26_otro) <- "Otro color (especifique):"
var_label(data$exposoma_27) <- "¿Ha notado algún olor fuerte o desagradable cuando se emiten estos humos o gases?"
var_label(data$exposoma_28) <- "Si respondió Sí, ¿cómo describiría el olor? "
var_label(data$exposoma_28_otro) <- "Otro (especifique):"
var_label(data$humo_impacto) <- "iv. Percepción del impacto ¿Cree que estas emisiones podrían estar afectando la salud de su familia o de su hijo?"
var_label(data$encuestador_9) <- "Encuestador"
var_label(data$fecha_hora_9) <- "Fecha y hora (fin)"
var_label(data$comentario_exposoma_6) <- "Comentario adicional"
var_label(data$cuestionario_de_padres_exposoma_complete) <- "Complete?"
var_label(data$entorno_hogar_1) <- "¿Cuántas personas viven en su vivienda?"
var_label(data$n_menor1) <- "Menores de 1 año"
var_label(data$n_2a5) <- "Entre 2 a 5 años"
var_label(data$n_6a17) <- "Entre 6 a 17 años"
var_label(data$n_18a59) <- "Entre 18 a 59 años"
var_label(data$n_mas60) <- "60 años a más"
var_label(data$entorno_hogar_3) <- "¿Cómo describiría dónde vive?"
var_label(data$entorno_hogar_3_otros) <- "Especifique que otro tipo de vivienda:"
var_label(data$sala) <- "Sala(s)"
var_label(data$dormitorio) <- "Dormitorio(s)"
var_label(data$otros_ambientes) <- "Otras ambientes (incluye cocina, baño(s)) "
var_label(data$sala_cortina) <- "Sala: cortinas"
var_label(data$sala_alfombra_fija) <- "Sala: alfombra fija (en el suelo)"
var_label(data$sala_tapete) <- "Sala: tapete (que puede retirarse)"
var_label(data$dormitorio_hijo_cortina) <- "Dormitorio de su hijo: cortinas"
var_label(data$dormitorio_hijo_alfombra) <- "Dormitorio de su hijo: alfombra fija (en el suelo)"
var_label(data$dormitorio_hijo_tapete) <- "Dormitorio de su hijo: tapete (que puede retirarse)"
var_label(data$bano_cortina) <- "Baño(s): cortinas"
var_label(data$bano_alfombra) <- "Baño(s): alfombra fija (en el suelo)"
var_label(data$bano_tapete) <- "Baño(s): tapete (que puede retirarse)"
var_label(data$sala_veces_ano) <- "Sala(s): veces al año que limpia"
var_label(data$dormitorio_veces_ano) <- "Dormitorio de su hijo: veces al año que limpia"
var_label(data$bano_veces_ano) <- "Baño(s): veces al año que limpia"
var_label(data$sala_forma_limpieza) <- "Sala(s): forma principal de limpieza"
var_label(data$dormitorio_forma_limpieza) <- "Dormitorio de su hijo: forma principal de limpieza"
var_label(data$bano_forma_limpieza) <- "Baño(s): forma principal de limpieza"
var_label(data$entorno_hogar_7) <- "¿De qué material principalmente están construidas las paredes exteriores de su casa/apartamento?"
var_label(data$entorno_hogar_7_otro) <- "Otro (especifique):"
var_label(data$entorno_hogar_8_sala) <- "Sala(s)"
var_label(data$entorno_hogar_8_dormitorio) <- "Dormitorio del niño"
var_label(data$entorno_hogar_8_banos) <- "Baño(s)"
var_label(data$entorno_hogar_9_frio) <- "Temporada invierno/ frío"
var_label(data$entorno_hogar_9_calor) <- "Temporada verano - primavera/ calor"
var_label(data$entorno_hogar_10) <- "¿En qué medida le molesta la contaminación del aire al dejar las ventanas abiertas?(Se refiere a gases, humo, polvo del tráfico, industrias o quema de basura)"
var_label(data$entorno_hogar_11) <- "¿Hacia dónde da la ventana del dormitorio de su hijo(a)?"
var_label(data$entorno_hogar_11_otros) <- "Otra vista, especifique:"
var_label(data$entorno_hogar_12_frio) <- "Temporada invierno/ frío"
var_label(data$entorno_hogar_12_calor) <- "Temporada verano - primavera/ calor"
var_label(data$entorno_hogar_13) <- "¿En qué piso se encuentra el dormitorio de su hijo(a)? (Ejemplo: 0 <- planta baja, 1 <- primer piso, etc.)"
var_label(data$entorno_hogar_14) <- "¿Cuántos pisos tiene en total su casa o edificio donde vive?"
var_label(data$entorno_hogar_15) <- "¿Qué tipo de colchón usa su hijo(a)?"
var_label(data$entorno_hogar_15_otros) <- "Otro (especifique):"
var_label(data$entorno_hogar_16) <- "¿Qué edad aproximada tiene ese colchón?"
var_label(data$entorno_hogar_17) <- "¿Tiene alguna mascota que viva principalmente dentro de la casa?"
var_label(data$entorno_hogar_17_gatos) <- "Si respondió Sí, complete la siguiente información: ¿Usted tiene gatos?"
var_label(data$gato_1) <- "¿Tiene gato(s)?"
var_label(data$gato_2) <- "¿Duermen dentro de la casa?"
var_label(data$gato_3) <- "¿Duermen en el mismo cuarto del niño(a)?"
var_label(data$gato_4) <- "¿El gato vivía en la casa cuando nació su hijo(a)?"
var_label(data$gato_5) <- "¿Cuántos gatos duermen dentro de la casa?"
var_label(data$gato_6) <- "¿Cuántos duermen en el cuarto del niño(a)?"
var_label(data$gato_7) <- "¿Hace cuánto convive el niño(a) con el gato/gatos? (años)"
var_label(data$gato_8) <- "¿Hace cuánto convive el niño(a) con el gato/gatos? (meses)"
var_label(data$entorno_hogar_17_perros) <- "¿Usted tiene perros?"
var_label(data$perro_1) <- "¿Tiene perro(s)?"
var_label(data$perro_2) <- "¿Duermen dentro de la casa?"
var_label(data$perro_3) <- "¿Duermen en el mismo cuarto del niño(a)?"
var_label(data$perro_4) <- "¿El perro vivía en la casa cuando nació su hijo(a)?"
var_label(data$perro_5) <- "¿Cuántos perros duermen dentro de la casa?"
var_label(data$perro_6) <- "¿Cuántos duermen en el cuarto del niño(a)?"
var_label(data$perro_7) <- "¿Hace cuánto convive el niño(a) con el perro(s)? (años)"
var_label(data$perro_8) <- "¿Hace cuánto convive el niño(a) con el perro(s)? (meses)"
var_label(data$entorno_hogar_17_aves) <- "¿Usted tiene aves (pajaritos, loros, etc.)?"
var_label(data$ave_1) <- "¿Tiene ave(s)?"
var_label(data$ave_2) <- "¿Duermen dentro de la casa?"
var_label(data$ave_3) <- "¿Duermen en el mismo cuarto del niño(a)?"
var_label(data$ave_4) <- "¿La(s) ave(s) vivía en la casa cuando nació su hijo(a)?"
var_label(data$ave_5) <- "¿Cuántos aves duermen dentro de la casa?"
var_label(data$ave_6) <- "¿Cuántos duermen en el cuarto del niño(a)?"
var_label(data$ave_7) <- "¿Hace cuánto convive el niño(a) con el ave(s)? (años)"
var_label(data$ave_8) <- "¿Hace cuánto convive el niño(a) con el ave(s)? (meses)"
var_label(data$entorno_hogar_17_corral) <- "¿Usted tiene animal de corral (palomas, gallinas, cuyes, etc.)?"
var_label(data$corral_1) <- "¿Tiene  animal(es) de corral (palomas, gallinas, cuyes, etc.)?"
var_label(data$corral_2) <- "¿Duermen dentro de la casa?"
var_label(data$corral_3) <- "¿Duermen en el mismo cuarto del niño(a)?"
var_label(data$corral_4) <- "¿Los animales de corral (palomas, gallinas, cuyes, etc.) vivían en la casa cuando nació su hijo(a)?"
var_label(data$corral_5) <- "¿Cuántos  animales de corral (palomas, gallinas, cuyes, etc.) duermen dentro de la casa?"
var_label(data$corral_6) <- "¿Cuántos duermen en el cuarto del niño(a)?"
var_label(data$corral_7) <- "¿Hace cuánto convive el niño(a) con los animales de corral (palomas, gallinas, cuyes, etc.)? (años)"
var_label(data$corral_8) <- "¿Hace cuánto convive el niño(a) con los animales de corral (palomas, gallinas, cuyes, etc.)? (meses)"
var_label(data$entorno_hogar_18_roedores) <- "Roedores"
var_label(data$entorno_cucarachas_18) <- "Cucarachas"
var_label(data$entorno_hogar_19) <- "¿Considera que su casa está húmeda?"
var_label(data$entorno_hogar_20) <- "¿Hay moho o manchas de moho dentro de su casa (excepto en los alimentos)?"
var_label(data$entorno_hogar_20_moho_1) <- "Habitación del niño(a)"
var_label(data$entorno_hogar_20_moho_2) <- "Resto de la casa"
var_label(data$entorno_hogar_20_moho_3) <- "Baño(s)"
var_label(data$entorno_hogar_20_moho_4) <- "Cocina"
var_label(data$entorno_hogar_20_moho_5) <- "Sótano / depósito"
var_label(data$entorno_hogar_22) <- "La casa donde vive actualmente su hijo(a), ¿es la misma donde usted vivía cuando estaba embarazada?"
var_label(data$entorno_hogar_23_1) <- "Distrito, departamento (desde el embarazo)"
var_label(data$entorno_hogar_23_1_1) <- "Dirección o referencia (desde el embarazo)"
var_label(data$entorno_hogar_23_1_2) <- "Tiempo vivido, en años (desde el embarazo)"
var_label(data$entorno_hogar_23_2) <- "Distrito, departamento (0 a 2 años)"
var_label(data$entorno_hogar_23_2_1) <- "Dirección o referencia (0 a 2 años)"
var_label(data$entorno_hogar_23_2_2) <- "Tiempo vivido, en años (0 a 2)"
var_label(data$entorno_hogar_23_3) <- "Distrito, departamento (3 a 5 años)"
var_label(data$entorno_hogar_23_3_1) <- "Dirección o referencia (3 a 5 años)"
var_label(data$entorno_hogar_23_3_2) <- "Tiempo vivido, en años (3 a 5)"
var_label(data$entorno_hogar_23_4) <- "Distrito, departamento (6 a 10 años)"
var_label(data$entorno_hogar_23_4_1) <- "Dirección o referencia (6 a 10 años)"
var_label(data$entorno_hogar_23_4_2) <- "Tiempo vivido, en años (6 a 10)"
var_label(data$entorno_hogar_23_5) <- "Distrito, departamento (actual)"
var_label(data$entorno_hogar_23_5_1) <- "Dirección o referencia (actual)"
var_label(data$entorno_hogar_23_5_2) <- "Tiempo vivido, en años (actual)"
var_label(data$entorno_hogar_24) <- "¿Existen edificaciones o vías en construcción, o calles sin pavimentar, a menos de una cuadra (100 metros) de su casa?"
var_label(data$entorno_hogar_25) <- "¿Existen fábricas, talleres o negocios cerca de su casa (a menos de una cuadra o 100 metros) Como: ladrilleras, madereras, calderas, quemas de llantas o basura, ¿talleres con humo o polvo?"
var_label(data$entorno_hogar_26) <- "Mientras su hijo(a) ha vivido en esta casa, ¿se han realizado obras, ampliaciones o remodelaciones Como: construcción, pintura, cambio de techo, pisos o paredes"
var_label(data$entorno_hogar_27) <- "¿La cocina está ubicada dentro del ambiente principal de la vivienda o en una zona exterior?"
var_label(data$entorno_hogar_28) <- "¿Su cocina cuenta con un extractor o campana de aire encima de la cocina?"
var_label(data$entorno_hogar_29) <- "Cuando cocina, ¿con qué frecuencia utiliza el extractor o campana de aire?"
var_label(data$entorno_hogar_30) <- "¿Qué tipo de cocina o estufa usa principalmente en su hogar? "
var_label(data$entorno_hogar_30_1) <- "Otro, especificar"
var_label(data$entorno_hogar_31) <- "¿Cuántas veces a la semana cocina utilizando una sartén antiadherente (teflón)?"
var_label(data$entorno_hogar_32_1) <- "Lejía/blanqueador"
var_label(data$entorno_hogar_32_2) <- "Amoníaco"
var_label(data$entorno_hogar_32_3) <- "Solvente quitamanchas"
var_label(data$entorno_hogar_32_4) <- "Limpiador de muebles"
var_label(data$entorno_hogar_32_5) <- "Limpiavidrios"
var_label(data$entorno_hogar_32_6) <- "Spray para alfombras, mantas o cortinas"
var_label(data$entorno_hogar_32_7) <- "Limpiador aromatizado de pisos"
var_label(data$entorno_hogar_32_8) <- "Limpiador de hornos o cocina"
var_label(data$entorno_hogar_32_9) <- "Ambientadores (en spray o eléctricos)"
var_label(data$entorno_hogar_32_10) <- "Spray para planchar ropa"
var_label(data$entorno_hogar_32_11) <- "Productos de limpieza perfumados"
var_label(data$entorno_hogar_32_12) <- "Limpiadores líquidos multiusos"
var_label(data$entorno_hogar_32_13) <- "Bolas de naftalina o similares"
var_label(data$entorno_hogar_32_14) <- "Aerosoles desengrasantes"
var_label(data$entorno_hogar_32_15) <- "Otros productos de limpieza (especifique):"
var_label(data$entorno_hogar_32_otro) <- "Otros productos de limpieza (especifique): "
var_label(data$entorno_hogar_33) <- "¿Con qué frecuencia limpia la vivienda (barrer, trapear, quitar polvo, etc.)?"
var_label(data$entorno_hogar_34) <- "¿Tienen aspiradora en su hogar?"
var_label(data$entorno_hogar_35) <- "Si tiene aspiradora, ¿esta cuenta con un filtro HEPA o de alta eficiencia?"
var_label(data$entorno_hogar_36) <- "¿Con qué frecuencia aspiran su vivienda?"
var_label(data$encuestador_10) <- "Encuestador"
var_label(data$fecha_hora_10) <- "Fecha y hora (fin)"
var_label(data$comentario_antropometria_7) <- "Comentario adicional"
var_label(data$cuestionario_de_padres_informacin_sobre_el_ambient_complete) <- "Complete?"
var_label(data$presion_sistolica_padre_1) <- "Presión arterial sistólica (Primera toma)"
var_label(data$presion_diastolica_padre_1) <- "Presión arterial diastólica (Primera toma)"
var_label(data$presion_sistolica_padre_2) <- "Presión arterial sistólica (segunda toma)"
var_label(data$presion_diastolica_padre_2) <- "Presión arterial sistólica (segunda toma)"
var_label(data$peso_padre) <- "Peso"
var_label(data$talla_padre_2) <- "Talla"
var_label(data$pcintura_padre) <- "Perímetro de cintura"
var_label(data$encuestador_11) <- "Encuestador"
var_label(data$fecha_hora_11) <- "Fecha y hora (fin)"
var_label(data$comentario_antropometria_8) <- "Comentario adicional"
var_label(data$cuestionario_de_padres_cartilla_clnica_de_los_padr_complete) <- "Complete?"
var_label(data$desayuno_biomarcadores) <- "¿El niño(a) desayunó antes de la recolección de la muestra de biomarcadores?"
var_label(data$colesterol_total) <- "Perfil lipídico: Colesterol total"
var_label(data$hdl_colesterol) <- "Perfil lipídico:HDL-colesterol (HDL-c)"
var_label(data$trigliceridos) <- "Perfil lipídico: Triglicéridos"
var_label(data$glucosa) <- "Glucosa"
var_label(data$encuestador_biomarcadores) <- "Encuestador"
var_label(data$fecha_hora_biomarcadores) <- "Fecha y hora (fin)"
var_label(data$comentario_biomarcadores) <- "Comentario adicional"
var_label(data$cuestionario_adolescentes_biomarcadores_complete) <- "Complete?"
var_label(data$alergia_pteronyssinus) <- "¿El niño(a) presentó reacción alérgica al ácaro del polvo Dermatophagoides pteronyssinus?"
var_label(data$alergia_farinae) <- "¿El niño(a) presentó reacción alérgica al ácaro del polvo Dermatophagoides farinae?"
var_label(data$alergia_destructor) <- "¿El niño(a) presentó reacción alérgica al ácaro Lepidoglyphus destructor?"
var_label(data$alergia_tropicalis) <- "¿El niño(a) presentó reacción alérgica al ácaro Blomia tropicalis?"
var_label(data$alergia_arcuatus) <- "¿El niño(a) presentó reacción alérgica al ácaro Chortoglyphus arcuatus?"
var_label(data$alergia_alternata) <- "¿El niño(a) presentó reacción alérgica al moho Alternaria alternata?"
var_label(data$alergia_herbarum) <- "¿El niño(a) presentó reacción alérgica al moho Cladosporium herbarum?"
var_label(data$alergia_fumigatus) <- "¿El niño(a) presentó reacción alérgica al moho Aspergillus fumigatus?"
var_label(data$alergia_notatum) <- "¿El niño(a) presentó sensibilización al moho Penicillium notatum?"
var_label(data$alergia_grasses) <- "¿El niño(a) presentó reacción alérgica a la mezcla de grasses?"
var_label(data$alergia_vulgaris) <- "¿El niño(a) presentó reacción alérgica a la Artemisia vulgaris?"
var_label(data$alergia_ambrosia) <- "¿El niño(a) presentó reacción alérgica a la Ambrosia?"
var_label(data$alergia_perro) <- "¿El niño(a) presentó reacción alérgica al epitelio de perro?"
var_label(data$alergia_gato) <- "¿El niño(a) presentó reacción alérgica al epitelio de gato?"
var_label(data$alergia_germanica) <- "¿El niño(a) presentó reacción alérgica a la cucaracha Blattella germanica?"
var_label(data$alergia_americana) <- "¿El niño(a) presentó reacción alérgica a la cucaracha Periplaneta americana?"
var_label(data$alergia_olivo) <- "¿El niño(a) presentó reacción alérgica al Olivo?"
var_label(data$asma) <- "¿Usted tiene asma?"
var_label(data$severidad_asma) <- "¿Qué severidad tiene su asma? (Para ser llenado por médico)"
var_label(data$rinitis_alergica) <- "¿Usted tiene rinitis alérgica?"
var_label(data$severidad_rinitis) <- "¿Qué severidad tiene su rinitis? (Para ser llenado por médico)"
var_label(data$sintomas_respiratorios_acaros_del_polvo_polvo_casero) <- "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice<-Ácaros del polvo (polvo casero))"
var_label(data$sintomas_respiratorios_hongos_o_moho) <- "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice<-Hongos o moho)"
var_label(data$sintomas_respiratorios_pelo_o_caspa_de_mascotas_perros_gatos) <- "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice<-Pelo o caspa de mascotas (perros, gatos, etc.))"
var_label(data$sintomas_respiratorios_polenes_de_arboles_plantas_o_flores) <- "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice<-Pólenes de árboles, plantas o flores)"
var_label(data$sintomas_respiratorios_ninguno_de_los_anteriores) <- "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice<-Ninguno de los anteriores)"
var_label(data$sintomas_respiratorios_unknown) <- "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice<-Unknown)"
var_label(data$sintomas_respiratorios_no_information) <- "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice<-No information)"
var_label(data$sintomas_respiratorios_invalid) <- "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice<-Invalid)"
var_label(data$sintomas_respiratorios_not_asked) <- "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice<-Not asked)"
var_label(data$isaac_asma_21) <- "¿Alguna vez has tenido silbidos o pitos en el pecho en el pasado?Si ha contestado NO, por favor salte a la pregunta ¿Algún médico te ha diagnosticado asma?"
var_label(data$isaac_asma_22) <- "En los últimos 12 meses, ¿has tenido silbidos o pitidos en el pecho?Si ha contestado NO, por favor salte a la pregunta ¿Algún médico te ha diagnosticado asma?"
var_label(data$isaac_asma_23) <- "¿Cuántos ataques de silbidos has tenido en los últimos 12 meses?"
var_label(data$isaac_asma_24) <- "En los últimos 12 meses, ¿cuántas noches por semana, en promedio, te ha despertado la sibilancia?"
var_label(data$isaac_asma_25) <- "En los últimos 12 meses, ¿la sibilancia ha limitado alguna vez tu habla a menos de una frase completa?"
var_label(data$isaac_asma_26) <- "¿Algún médico te ha diagnosticado asma?"
var_label(data$isaac_asma_27) <- "En los últimos 12 meses, ¿has tenido silbidos asociados al ejercicio físico (durante la práctica de deporte)?"
var_label(data$isaac_asma_28) <- "En los últimos 12 meses, ¿has tenido una tos seca nocturna sin estar resfriado o teniendo gripe?"
var_label(data$isaac_rinitis_29) <- "¿Alguna vez has tenido un problema nasal (estornudos, goteo o congestión nasal) sin estar resfriado o con gripe? Si ha contestado NO, por favor salte a la pregunta ¿Un médico te ha diagnosticado rinitis alérgica (alergia nasal)?"
var_label(data$isaac_rinitis_30) <- "¿En los últimos 12 meses has tenido un problema nasal (estornudos, goteo o congestión nasal) sin estar resfriado o con gripe? Si ha contestado NO, por favor salte a la pregunta ¿Un médico te ha diagnosticado rinitis alérgica (alergia nasal)?"
var_label(data$isaac_rinitis_31) <- "¿Cuántos meses al año, aproximadamente, suele afectarte este problema nasal?"
var_label(data$isaac_rinitis_32) <- "¿Estos síntomas nasales, durante los últimos 12 meses, han limitado tu actividad normal (jugar, ir a la escuela, hacer deporte)?"
var_label(data$isaac_rinitis_33) <- "¿Has tenido comezón y lagrimeo ocular junto con los síntomas nasales en los últimos 12 meses?"
var_label(data$isaac_rinitis_34) <- "¿Un médico te ha diagnosticado rinitis alérgica (alergia nasal)?"
var_label(data$isaac_dermatitis_35) <- "¿Alguna vez has tenido erupción de picor que haya durado más de una semana? Si ha contestado NO, por favor salte a la pregunta ¿Un médico te ha diagnosticado eczema o dermatitis atópica?"
var_label(data$isaac_dermatitis_36) <- "¿En los últimos 12 meses has tenido una erupción de picor? Si ha contestado NO, por favor salte a la pregunta ¿Un médico te ha diagnosticado eczema o dermatitis atópica?"
var_label(data$isaac_dermatitis_37) <- "¿En los últimos 12 meses, has tenido esa erupción de picor en alguno de estos sitios: dentro de los codos, detrás de las rodillas, al frente de los tobillos, bajo las nalgas, alrededor del cuello, ¿los ojos u orejas?"
var_label(data$isaac_dermatitis_38) <- "¿En los últimos 12 meses, ¿la erupción ha desaparecido completamente durante algún período?"
var_label(data$isaac_dermatitis_39) <- "¿La erupción de picor ha afectado tu sueño en los últimos 12 meses? Si es así, ¿con qué frecuencia?"
var_label(data$isaac_dermatitis_40) <- "¿Un médico te ha diagnosticado eczema o dermatitis atópica?"
var_label(data$feno) <- "FENORegistrar el valor de la fracción exhalada de óxido nítrico (FeNO) obtenido con el dispositivo calibrado"
var_label(data$encuestador_alergias) <- "Encuestador"
var_label(data$fecha_hora_alergias) <- "Fecha y hora (fin)"
var_label(data$comentario_alergias) <- "Comentario adicional"
var_label(data$cuestionario_adolescentes_alergias_complete) <- "Complete?"
var_label(data$peso_1) <- "Peso - Toma 1"
var_label(data$peso_2) <- "Peso - Toma 2"
var_label(data$peso_3) <- "Peso - Toma 3"
var_label(data$talla_1) <- "Talla - Toma 1"
var_label(data$talla_2) <- "Talla - Toma 2"
var_label(data$talla_3) <- "Talla - Toma 3"
var_label(data$talla_sentado_1) <- "Talla sentado - Toma 1"
var_label(data$talla_sentado_2) <- "Talla sentado - Toma 2"
var_label(data$talla_sentado_3) <- "Talla sentado - Toma 3"
var_label(data$pliegue_bicipital_1) <- "Pliegue bicipital - Toma 1"
var_label(data$pliegue_bicipital_2) <- "Pliegue bicipital - Toma 2"
var_label(data$pliegue_bicipital_3) <- "Pliegue bicipital - Toma 3"
var_label(data$pliegue_triceps_1) <- "Pliegue tricipital - Toma 1"
var_label(data$pliegue_triceps_2) <- "Pliegue tricipital - Toma 2"
var_label(data$pliegue_triceps_3) <- "Pliegue tricipital - Toma 3"
var_label(data$pliegue_subescapular_1) <- "Pliegue subescapular - Toma 1"
var_label(data$pliegue_subescapular_2) <- "Pliegue subescapular - Toma 2"
var_label(data$pliegue_subescapular_3) <- "Pliegue subescapular - Toma 3"
var_label(data$pliegue_pierna_1) <- "Pliegue de pierna - Toma 1"
var_label(data$pliegue_pierna_2) <- "Pliegue de pierna - Toma 2"
var_label(data$pliegue_pierna_3) <- "Pliegue de pierna - Toma 3"
var_label(data$perimetro_cuello_1) <- "Perímetro de cuello - Toma 1"
var_label(data$perimetro_cuello_2) <- "Perímetro de cuello - Toma 2"
var_label(data$perimetro_cuello_3) <- "Perímetro de cuello - Toma 3"
var_label(data$perimetro_cintura_1) <- "Perímetro de cintura - Toma 1"
var_label(data$perimetro_cintura_2) <- "Perímetro de cintura - Toma 2"
var_label(data$perimetro_cintura_3) <- "Perímetro de cintura - Toma 3"
var_label(data$perimetro_cadera_1) <- "Perímetro de cadera - Toma 1"
var_label(data$perimetro_cadera_2) <- "Perímetro de cadera - Toma 2"
var_label(data$perimetro_cadera_3) <- "Perímetro de cadera - Toma 3"
var_label(data$masa_grasa_corporal) <- "Porcentaje de masa grasa corporal (bioimpedancia)"
var_label(data$grasa_visceral) <- "Porcentaje de grasa visceral (bioimpedancia)"
var_label(data$vo2max_fc_final) <- "Frecuencia cardíaca final: Frecuencia cardíaca al finalizar los 3 minutos (bpm)"
var_label(data$vo2max_sato2) <- "Saturación de oxígeno: Saturación de oxígeno al finalizar los 3 minutos (SaO₂ %)"
var_label(data$dinamo_1) <- "Dinamómetro - Toma 1"
var_label(data$dinamo_2) <- "Dinamómetro - Toma 2"
var_label(data$dinamo_3) <- "Dinamómetro - Toma 3"
var_label(data$dinamo_max) <- "Mejor fuerza (valor máximo)"
var_label(data$encuestador_antropometria) <- "Encuestador"
var_label(data$fecha_hora_antropometria) <- "Fecha y hora (fin)"
var_label(data$comentario_antropometria) <- "Comentario adicional"
var_label(data$cuestionario_adolescentes_antropometria_complete) <- "Complete?"
var_label(data$pas_1) <- "Presión arterial sistólica (PAS) - Toma 1"
var_label(data$pas_2) <- "Presión arterial sistólica (PAS) - Toma 2"
var_label(data$pas_3) <- "Presión arterial sistólica (PAS) - Toma 3"
var_label(data$pad_1) <- "Presión arterial diastólica (PAD) - Toma 1"
var_label(data$pad_2) <- "Presión arterial diastólica (PAD) - Toma 2"
var_label(data$pad_3) <- "Presión arterial diastólica (PAD) - Toma 3"
var_label(data$pulso_1) <- "Frecuencia cardiaca (pulso) - Toma 1"
var_label(data$pulso_2) <- "Frecuencia cardiaca (pulso) - Toma 2"
var_label(data$pulso_3) <- "Frecuencia cardiaca (pulso) - Toma 3"
var_label(data$encuestador_parterial) <- "Encuestador"
var_label(data$fecha_hora_parterial) <- "Fecha y hora (fin)"
var_label(data$comentario_parterial) <- "Comentario adicional"
var_label(data$cuestionario_adolescentes_presion_arterial_complete) <- "Complete?"
var_label(data$sintomas_depresivos_1) <- "¿Te has sentido deprimido(a), irritable o sin esperanza?"
var_label(data$sintomas_depresivos_2) <- "¿Has tenido poco interés o placer en hacer cosas?"
var_label(data$sintomas_depresivos_3) <- "¿Has tenido dificultad para dormirte, mantenerte dormido(a) o has dormido demasiado?"
var_label(data$sintomas_depresivos_4) <- "¿Has tenido poco apetito, pérdida de peso o has comido en exceso?"
var_label(data$sintomas_depresivos_5) <- "¿Te has sentido cansado(a) o con poca energía?"
var_label(data$sintomas_depresivos_6) <- "¿Has sentido que has fallado a tu familia o a ti mismo(a)?"
var_label(data$sintomas_depresivos_7) <- "¿Has tenido problemas para concentrarte en tareas escolares, leer o ver televisión?"
var_label(data$sintomas_depresivos_8) <- "¿Te has movido o hablado tan lentamente que otras personas lo notan? ¿O has estado inquieto(a), moviéndote más de lo usual?"
var_label(data$sintomas_depresivos_9) <- "¿Has tenido pensamientos de que estarías mejor muerto(a) o de hacerte daño de alguna manera?"
var_label(data$sintomas_ansiedad_1) <- "Sentí momentos de terror, miedo o susto repentino."
var_label(data$sintomas_ansiedad_2) <- "Me sentí ansioso(a), preocupado(a) o nervioso(a)."
var_label(data$sintomas_ansiedad_3) <- "Tuve pensamientos sobre cosas malas que podrían pasar, como una tragedia familiar, enfermedad, pérdida de trabajo o accidentes."
var_label(data$sintomas_ansiedad_4) <- "Sentí el corazón acelerado, sudoración, dificultad para respirar, mareo o temblores."
var_label(data$sintomas_ansiedad_5) <- "Sentí los músculos tensos, estaba inquieto(a) o con dificultad para relajarme o dormir."
var_label(data$sintomas_ansiedad_6) <- "Evité o no me acerqué a situaciones que me causaban preocupación."
var_label(data$sintomas_ansiedad_7) <- "Me retiré temprano de situaciones o participé muy poco debido a mis preocupaciones."
var_label(data$sintomas_ansiedad_8) <- "Pasé mucho tiempo tomando decisiones, postergando decisiones o preparándome para situaciones por mis preocupaciones."
var_label(data$sintomas_ansiedad_9) <- "Busqué tranquilidad o confirmación de otras personas debido a mis preocupaciones."
var_label(data$sintomas_ansiedad_10) <- "Necesité ayuda para sobrellevar mi ansiedad (por ejemplo, alcohol, medicación, objetos supersticiosos o apoyo de otras personas)."
var_label(data$nutricion_1) <- "Cuando almuerzo fuera de casa, suelo elegir una opción baja en grasa."
var_label(data$nutricion_2) <- "Suelo evitar comer frituras."
var_label(data$nutricion_3) <- "Suelo comer postres si hay disponibles."
var_label(data$nutricion_4) <- "Me aseguro de comer al menos una porción de fruta al día."
var_label(data$nutricion_5) <- "Trato de mantener bajo mi consumo total de grasa."
var_label(data$nutricion_6) <- "Si compro papas fritas (snacks), elijo una marca baja en grasa."
var_label(data$nutricion_7) <- "Evito comer muchas salchichas y hamburguesas."
var_label(data$nutricion_8) <- "Suelo comprar dulces o tortas."
var_label(data$nutricion_9) <- "Trato de mantener bajo mi consumo total de azúcar."
var_label(data$nutricion_10) <- "Como al menos una porción de verduras o ensalada al día."
var_label(data$nutricion_11) <- "Si como postre en casa, intento que sea bajo en grasa."
var_label(data$nutricion_12) <- "Rara vez como comida para llevar."
var_label(data$nutricion_13) <- "Trato de comer muchas frutas y verduras."
var_label(data$nutricion_14) <- "Suelo comer dulces o snacks entre comidas."
var_label(data$nutricion_15) <- "Generalmente como al menos una porción de verduras (sin contar papas) o ensalada por la noche."
var_label(data$nutricion_16) <- "Cuando compro una bebida gaseosa, elijo una versión dietética."
var_label(data$nutricion_17) <- "Cuando pongo mantequilla/margarina en el pan, uso una capa delgada."
var_label(data$nutricion_18) <- "Si llevo lonchera, normalmente incluyo chocolate o galletas."
var_label(data$nutricion_19) <- "Si como un snack entre comidas, suelo elegir fruta."
var_label(data$nutricion_20) <- "Si como postre en un restaurante, elijo el más saludable disponible."
var_label(data$nutricion_21) <- "Suelo poner crema a los postres."
var_label(data$nutricion_22) <- "Como al menos tres porciones de fruta la mayoría de días."
var_label(data$nutricion_23) <- "En general, trato de llevar una dieta saludable."
var_label(data$paqc_1) <- "Durante los últimos 7 días, en tus clases de educación física, ¿con qué frecuencia estuviste muy activo(a)?"
var_label(data$paqc_2) <- "Durante los últimos 7 días, ¿qué hiciste durante el recreo?"
var_label(data$paqc_3) <- "Durante los últimos 7 días, ¿qué hiciste en la hora de almuerzo (además de comer)?"
var_label(data$paqc_4) <- "Durante los últimos 7 días, inmediatamente después del colegio ¿cuántos días practicaste deporte, bailaste o jugaste en los que estuvieras muy activo? "
var_label(data$paqc_5) <- "Durante los últimos 7 días, ¿en cuántas noches hiciste deporte, bailaste o jugaste activamente? "
var_label(data$paqc_6) <- "Durante el último fin de semana, ¿cuántas veces hiciste deporte, bailaste o jugaste activamente? "
var_label(data$paqc_7) <- "¿Cuál de las siguientes opciones te describe mejor en los últimos 7 días?"
var_label(data$paqc_8_1_ninguna) <- "Lunes (choice<-Ninguna)"
var_label(data$paqc_8_1_a_veces) <- "Lunes (choice<-A veces)"
var_label(data$paqc_8_1_regular) <- "Lunes (choice<-Regular)"
var_label(data$paqc_8_1_frecuente) <- "Lunes (choice<-Frecuente)"
var_label(data$paqc_8_1_muy_frecuente) <- "Lunes (choice<-Muy frecuente)"
var_label(data$paqc_8_1_unknown) <- "Lunes (choice<-Unknown)"
var_label(data$paqc_8_1_no_information) <- "Lunes (choice<-No information)"
var_label(data$paqc_8_1_invalid) <- "Lunes (choice<-Invalid)"
var_label(data$paqc_8_1_not_asked) <- "Lunes (choice<-Not asked)"
var_label(data$paqc_8_2_ninguna) <- "Martes (choice<-Ninguna)"
var_label(data$paqc_8_2_a_veces) <- "Martes (choice<-A veces)"
var_label(data$paqc_8_2_regular) <- "Martes (choice<-Regular)"
var_label(data$paqc_8_2_frecuente) <- "Martes (choice<-Frecuente)"
var_label(data$paqc_8_2_muy_frecuente) <- "Martes (choice<-Muy frecuente)"
var_label(data$paqc_8_2_unknown) <- "Martes (choice<-Unknown)"
var_label(data$paqc_8_2_no_information) <- "Martes (choice<-No information)"
var_label(data$paqc_8_2_invalid) <- "Martes (choice<-Invalid)"
var_label(data$paqc_8_2_not_asked) <- "Martes (choice<-Not asked)"
var_label(data$paqc_8_3_ninguna) <- "Miércoles (choice<-Ninguna)"
var_label(data$paqc_8_3_a_veces) <- "Miércoles (choice<-A veces)"
var_label(data$paqc_8_3_regular) <- "Miércoles (choice<-Regular)"
var_label(data$paqc_8_3_frecuente) <- "Miércoles (choice<-Frecuente)"
var_label(data$paqc_8_3_muy_frecuente) <- "Miércoles (choice<-Muy frecuente)"
var_label(data$paqc_8_3_unknown) <- "Miércoles (choice<-Unknown)"
var_label(data$paqc_8_3_no_information) <- "Miércoles (choice<-No information)"
var_label(data$paqc_8_3_invalid) <- "Miércoles (choice<-Invalid)"
var_label(data$paqc_8_3_not_asked) <- "Miércoles (choice<-Not asked)"
var_label(data$paqc_8_4_ninguna) <- "Jueves (choice<-Ninguna)"
var_label(data$paqc_8_4_a_veces) <- "Jueves (choice<-A veces)"
var_label(data$paqc_8_4_regular) <- "Jueves (choice<-Regular)"
var_label(data$paqc_8_4_frecuente) <- "Jueves (choice<-Frecuente)"
var_label(data$paqc_8_4_muy_frecuente) <- "Jueves (choice<-Muy frecuente)"
var_label(data$paqc_8_4_unknown) <- "Jueves (choice<-Unknown)"
var_label(data$paqc_8_4_no_information) <- "Jueves (choice<-No information)"
var_label(data$paqc_8_4_invalid) <- "Jueves (choice<-Invalid)"
var_label(data$paqc_8_4_not_asked) <- "Jueves (choice<-Not asked)"
var_label(data$paqc_8_5_ninguna) <- "Viernes (choice<-Ninguna)"
var_label(data$paqc_8_5_a_veces) <- "Viernes (choice<-A veces)"
var_label(data$paqc_8_5_regular) <- "Viernes (choice<-Regular)"
var_label(data$paqc_8_5_frecuente) <- "Viernes (choice<-Frecuente)"
var_label(data$paqc_8_5_muy_frecuente) <- "Viernes (choice<-Muy frecuente)"
var_label(data$paqc_8_5_unknown) <- "Viernes (choice<-Unknown)"
var_label(data$paqc_8_5_no_information) <- "Viernes (choice<-No information)"
var_label(data$paqc_8_5_invalid) <- "Viernes (choice<-Invalid)"
var_label(data$paqc_8_5_not_asked) <- "Viernes (choice<-Not asked)"
var_label(data$paqc_8_6_ninguna) <- "Sábado (choice<-Ninguna)"
var_label(data$paqc_8_6_a_veces) <- "Sábado (choice<-A veces)"
var_label(data$paqc_8_6_regular) <- "Sábado (choice<-Regular)"
var_label(data$paqc_8_6_frecuente) <- "Sábado (choice<-Frecuente)"
var_label(data$paqc_8_6_muy_frecuente) <- "Sábado (choice<-Muy frecuente)"
var_label(data$paqc_8_6_unknown) <- "Sábado (choice<-Unknown)"
var_label(data$paqc_8_6_no_information) <- "Sábado (choice<-No information)"
var_label(data$paqc_8_6_invalid) <- "Sábado (choice<-Invalid)"
var_label(data$paqc_8_6_not_asked) <- "Sábado (choice<-Not asked)"
var_label(data$paqc_8_7_ninguna) <- "Domingo (choice<-Ninguna)"
var_label(data$paqc_8_7_a_veces) <- "Domingo (choice<-A veces)"
var_label(data$paqc_8_7_regular) <- "Domingo (choice<-Regular)"
var_label(data$paqc_8_7_frecuente) <- "Domingo (choice<-Frecuente)"
var_label(data$paqc_8_7_muy_frecuente) <- "Domingo (choice<-Muy frecuente)"
var_label(data$paqc_8_7_unknown) <- "Domingo (choice<-Unknown)"
var_label(data$paqc_8_7_no_information) <- "Domingo (choice<-No information)"
var_label(data$paqc_8_7_invalid) <- "Domingo (choice<-Invalid)"
var_label(data$paqc_8_7_not_asked) <- "Domingo (choice<-Not asked)"
var_label(data$paqc_9) <- "¿Estuviste enfermo(a) esta última semana o algo impidió que hicieras normalmente actividad física?"
var_label(data$paqc_9_1) <- "Si marcó sí, especifique el motivo de enfermedad:"
var_label(data$encuestador_saludmental) <- "Encuestador"
var_label(data$fecha_hora_saludmental) <- "Fecha y hora (fin)"
var_label(data$comentario_saludmental) <- "Comentario adicional"
var_label(data$cuestionario_adolescentes_salud_mental_complete) <- "Complete?"
var_label(data$presion_atm) <- "Presión atmosférica"
var_label(data$temperatura_ambiente) <- "Temperatura ambiente"
var_label(data$humedad) <- "Humedad relativa"
var_label(data$altitud) <- "Altitud"
var_label(data$cirujia) <- "¿Cirugía de ojo, corazón, pecho, pulmón, o abdominal en los últimos 3 meses?"
var_label(data$ataque_corazon) <- "¿Un ataque al corazón en los últimos 3 meses?"
var_label(data$presion_espirometria) <- "¿Presión arterial mayor que 180 (sistólico) / 120 (diastólico)?"
var_label(data$pulso_espirometria) <- "¿Pulso mayor que 120 latidos/min?"
var_label(data$infeccion_respiratoria) <- "¿Infección respiratoria en las últimas 2 semanas?"
var_label(data$broncodilatador_12h) <- "¿Broncodilatador de acción prolongada en las últimas 12 horas?"
var_label(data$broncodilatador_4h) <- "¿Broncodilatador de acción corta en las últimas 4 horas?"
var_label(data$fumo) <- "¿Fumó en la última hora?"
var_label(data$fiebre) <- "Fiebre"
var_label(data$tos) <- "Tos"
var_label(data$dolor_garganta) <- "Dolor de garganta"
var_label(data$flema) <- "Flema"
var_label(data$escalofrios) <- "Escalofríos"
var_label(data$dolor_cuerpo) <- "Dolor de cuerpo"
var_label(data$fatiga) <- "Fatiga"
var_label(data$dolor_cabeza) <- "Dolor de cabeza"
var_label(data$congestion) <- "Congestión nasal"
var_label(data$goteo) <- "Goteo de nariz"
var_label(data$estornudos) <- "Estornudos"
var_label(data$id_espirometro) <- "ID de espirómetro"
var_label(data$espirometria) <- "¿Realizada?"
var_label(data$fvc) <- "Capacidad vital forzada (CVF o FVC)"
var_label(data$fev1) <- "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
var_label(data$fev1_fvc) <- "FEV1/FVC"
var_label(data$pef) <- "Flujo espiratorio máximo (PEF o FEF)"
var_label(data$fev3) <- "Volumen espiratorio forzado en tres segundos (FEV3)"
var_label(data$fev6) <- "Volumen espiratorio forzado en seis segundos (FEV6)"
var_label(data$error_espirometria) <- "Error"
var_label(data$espirometria_aceptable) <- "¿Aceptable?"
var_label(data$espirometria_2) <- "¿Realizada?"
var_label(data$fvc_2) <- "Capacidad vital forzada (CVF o FVC)"
var_label(data$fev1_2) <- "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
var_label(data$fev1_fvc_2) <- "FEV1/FVC"
var_label(data$pef_2) <- "Flujo espiratorio máximo (PEF o FEF)"
var_label(data$fev3_2) <- "Volumen espiratorio forzado en tres segundos (FEV3)"
var_label(data$fev6_2) <- "Volumen espiratorio forzado en seis segundos (FEV6)"
var_label(data$error_espirometria_2) <- "Error"
var_label(data$espirometria_aceptable_2) <- "¿Aceptable?"
var_label(data$espirometria_3) <- "¿Realizada?"
var_label(data$fvc_3) <- "Capacidad vital forzada (CVF o FVC)"
var_label(data$fev1_3) <- "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
var_label(data$fev1_fvc_3) <- "FEV1/FVC"
var_label(data$pef_3) <- "Flujo espiratorio máximo (PEF o FEF)"
var_label(data$fev3_3) <- "Volumen espiratorio forzado en tres segundos (FEV3)"
var_label(data$fev6_3) <- "Volumen espiratorio forzado en seis segundos (FEV6)"
var_label(data$error_espirometria_3) <- "Error"
var_label(data$espirometria_aceptable_3) <- "¿Aceptable?"
var_label(data$espirometria_4) <- "¿Realizada?"
var_label(data$fvc_4) <- "Capacidad vital forzada (CVF o FVC)"
var_label(data$fev1_4) <- "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
var_label(data$fev1_fvc_4) <- "FEV1/FVC"
var_label(data$pef_4) <- "Flujo espiratorio máximo (PEF o FEF)"
var_label(data$fev3_4) <- "Volumen espiratorio forzado en tres segundos (FEV3)"
var_label(data$fev6_4) <- "Volumen espiratorio forzado en seis segundos (FEV6)"
var_label(data$error_espirometria_4) <- "Error"
var_label(data$espirometria_aceptable_4) <- "¿Aceptable?"
var_label(data$espirometria_5) <- "¿Realizada?"
var_label(data$fvc_5) <- "Capacidad vital forzada (CVF o FVC)"
var_label(data$fev1_5) <- "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
var_label(data$fev1_fvc_5) <- "FEV1/FVC"
var_label(data$pef_5) <- "Flujo espiratorio máximo (PEF o FEF)"
var_label(data$fev3_5) <- "Volumen espiratorio forzado en tres segundos (FEV3)"
var_label(data$fev6_5) <- "Volumen espiratorio forzado en seis segundos (FEV6)"
var_label(data$error_espirometria_5) <- "Error"
var_label(data$espirometria_aceptable_5) <- "¿Aceptable?"
var_label(data$espirometria_6) <- "¿Realizada?"
var_label(data$fvc_6) <- "Capacidad vital forzada (CVF o FVC)"
var_label(data$fev1_6) <- "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
var_label(data$fev1_fvc_6) <- "FEV1/FVC"
var_label(data$pef_6) <- "Flujo espiratorio máximo (PEF o FEF)"
var_label(data$fev3_6) <- "Volumen espiratorio forzado en tres segundos (FEV3)"
var_label(data$fev6_6) <- "Volumen espiratorio forzado en seis segundos (FEV6)"
var_label(data$error_espirometria_6) <- "Error"
var_label(data$espirometria_aceptable_6) <- "¿Aceptable?"
var_label(data$espirometria_7) <- "¿Realizada?"
var_label(data$fvc_7) <- "Capacidad vital forzada (CVF o FVC)"
var_label(data$fev1_7) <- "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
var_label(data$fev1_fvc_7) <- "FEV1/FVC"
var_label(data$pef_7) <- "Flujo espiratorio máximo (PEF o FEF)"
var_label(data$fev3_7) <- "Volumen espiratorio forzado en tres segundos (FEV3)"
var_label(data$fev6_7) <- "Volumen espiratorio forzado en seis segundos (FEV6)"
var_label(data$error_espirometria_7) <- "Error"
var_label(data$espirometria_aceptable_7) <- "¿Aceptable?"
var_label(data$espirometria_8) <- "¿Realizada?"
var_label(data$fvc_8) <- "Capacidad vital forzada (CVF o FVC)"
var_label(data$fev1_8) <- "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
var_label(data$fev1_fvc_8) <- "FEV1/FVC"
var_label(data$pef_8) <- "Flujo espiratorio máximo (PEF o FEF)"
var_label(data$fev3_8) <- "Volumen espiratorio forzado en tres segundos (FEV3)"
var_label(data$fev6_8) <- "Volumen espiratorio forzado en seis segundos (FEV6)"
var_label(data$error_espirometria_8) <- "Error"
var_label(data$espirometria_aceptable_8) <- "¿Aceptable?"
var_label(data$razon_detener) <- "Razón para detenerse"
var_label(data$razon_otros) <- "Si Otro (especifique)"
var_label(data$fecha_revision) <- "Fecha de revisión"
var_label(data$revision_curvas) <- "¿Hay al menos 3 curvas aceptables y 2 reproducibles? "
var_label(data$fvc_revision) <- "Capacidad vital forzada (CVF o FVC)"
var_label(data$fev1_revision) <- "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
var_label(data$fev1_fvc_revision) <- "FEV1/FVC"
var_label(data$pef_revision) <- "Flujo espiratorio máximo (PEF o FEF)"
var_label(data$fev3_revision) <- "Volumen espiratorio forzado en tres segundos (FEV3)"
var_label(data$fev6_revision) <- "Volumen espiratorio forzado en seis segundos (FEV6)"
var_label(data$clasificacion_revision) <- "Calificación: espirometría"
var_label(data$encuestador_6) <- "Encuestador"
var_label(data$fecha_hora_6) <- "Fecha y hora (fin)"
var_label(data$comentario_espirometria_6) <- "Comentario adicional"
var_label(data$cuestionario_adolescentes_vi_espirometra_complete) <- "Complete?"
var_label(data$formulario_final) <- "¿Qué encuestador completó el formulario?"
var_label(data$fecha_hora_fin) <- "Fecha y hora de fin"
var_label(data$fin_de_cuestionarios_complete) <- "Complete?"

