library(Hmisc)

label(data$record_id) = "Record ID"
label(data$redcap_event_name) = "Event Name"
label(data$redcap_repeat_instrument) = "Repeat Instrument"
label(data$redcap_repeat_instance) = "Repeat Instance"
label(data$colegio_id) = "¿A qué colegio pertenece?"
label(data$numero_visita) = "Número de visita"
label(data$consentimiento_1) = "¿El padre, madre o tutor legal firmó el consentimiento informado para autorizar la participación del menor en este estudio?"
label(data$consentimiento_2) = "¿El padre, madre o tutor legal firmó el consentimiento informado para participar en este estudio?"
label(data$consentimiento_nombre) = "Nombre de la persona que firmó el consentimiento informado"
label(data$consenti_relacion) = "Relación con el niño/adolescente"
label(data$consenti_relacion_otro) = "Otro (especifique):________________________"
label(data$asentimiento_1) = "¿El niño/adolescente recibió la hoja de asentimiento en un lenguaje adecuado para su edad?"
label(data$asentimiento_2) = "¿El niño/adolescente expresó libremente su deseo de participar en el estudio (asentimiento informado)?"
label(data$asentimiento_nombre) = "Nombre de la persona que firmó el consentimiento informado"
label(data$consent_asent_investig) = "El encuestador/investigador verificó la firma del consentimiento y asentimiento."
label(data$encuestador_0) = "Encuestador"
label(data$fecha_hora_0) = "Fecha y hora (fin)"
label(data$comentario_0) = "Comentario adicional"
label(data$cuestionario_adolescentes_0_consent_asent_complete) = "Complete?"
label(data$pariente_del_infante) = "¿Quién completa el formulario?"
label(data$pariente_del_infante_2) = "Otro pariente (especifique):"
label(data$nombre_apoderado) = "Nombre y Apellidos del familiar (madre/padre/apoderado)"
label(data$fecha_nacimiento_pariente) = "Fecha de nacimiento de la madre/padre/pariente:"
label(data$edad_pariente) = "Edad autorreportada de la madre/padre/pariente"
label(data$celular_pariente) = "Celular de la madre/padre/apoderado"
label(data$estado_civil_pariente) = "¿Cuál es su estado civil?"
label(data$estad_civil_pariente) = "Actualmente usted: "
label(data$nivel_educativo_pariente) = "¿Cuál es su nivel educativo?Del padre/madre/apoderado que está llenando la encuesta"
label(data$situacion_laboral_pariente) = "¿Cuál es su situación laboral actual?"
label(data$laboral_pariente_1) = "Otra, especifique: "
label(data$sit_economica_1) = "¿Cómo describiría la situación económica actual de su familia?"
label(data$sit_economica_2) = "En comparación con hace cinco años, ¿cómo considera que está la situación económica de su familia ahora?"
label(data$sit_economica_3) = "En comparación con hace cinco años, ¿cómo considera que está la situación económica de su familia ahora?"
label(data$seguro_de_salud_adolescente) = "¿Qué tipo de seguro de salud tiene el adolescente?"
label(data$direccion_distrito) = "¿En qué dirección y distrito vive actualmente? Es necesario poner la dirección exacta"
label(data$ano_residencia) = "¿Hace cuánto tiempo vive en este domicilio en años?"
label(data$nombre_hijo) = "Nombre y Apellidos del niño que será evaluado"
label(data$orden_del_hijo) = "¿Qué orden ocupa el niño(a) participante (su hijo) entre sus hijos(as)?"
label(data$fecgha_nacimiento_adolescente) = "Fecha de nacimiento del el participante (su hijo) "
label(data$edad_adolescente) = "Edad adolescente (autorreportada por el padre)"
label(data$lactancia_materna) = "Con respecto a la lactancia materna, el participante (su hijo):¿Recibió leche materna exclusiva hasta los 6 meses de edad ?"
label(data$lactancia_materna_2) = "¿Qué edad tenía su hijo cuando dejó de recibir leche materna por completo? "
label(data$lactancia_materna_2_meses) = "Indicar en meses"
label(data$lactancia_materna_3) = "¿A qué edad comenzó a tomar leche de fórmula?"
label(data$lactancia_materna_3_meses) = "Indicar en meses"
label(data$lactancia_materna_4) = "¿A qué edad comenzó la alimentación complementaria (por ejemplo, papillas)? "
label(data$lactancia_materna_4_meses) = "Indicar meses"
label(data$hospitalizado_nino_nacer) = "Durante el primer año de nacido, ¿el adolescente (su hijo) fue hospitalizado al nacer?"
label(data$hospitalizado_nino_nacer_1) = "Si marcó Sí, indique la duración de la hospitalización:"
label(data$enf_bajopeso_prematuro) = "¿El adolescente nació con bajo peso o de forma prematura (antes de las 37 semanas de gestación)?"
label(data$enf_macrosomia) = "¿El adolescente nació con macrosomía (peso mayor de 4 kilos al nacer)?"
label(data$enf_pulmonares_rinitis_alergica) = "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice=Rinitis alérgica)"
label(data$enf_pulmonares_asma) = "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice=Asma)"
label(data$enf_pulmonares_dermatitis_atopica) = "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice=Dermatitis atópica)"
label(data$enf_pulmonares_bronquitis_cronica) = "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice=Bronquitis crónica)"
label(data$enf_pulmonares_ninguna) = "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice=Ninguna)"
label(data$enf_pulmonares_unknown) = "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice=Unknown)"
label(data$enf_pulmonares_no_information) = "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice=No information)"
label(data$enf_pulmonares_invalid) = "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice=Invalid)"
label(data$enf_pulmonares_not_asked) = "¿El adolescente ha sido diagnosticado alguna vez con alguna de las siguientes enfermedades? (choice=Not asked)"
label(data$enf_dm1) = "¿El adolescente ha sido diagnosticado con diabetes tipo 1?"
label(data$enf_resit_insulina) = "¿El adolescente ha presentado resistencia a la insulina?"
label(data$enf_dislipidemias) = "¿El adolescente  ha sido diagnosticado con dislipidemia (colesterol o triglicéridos elevados o ambas)?"
label(data$inf_respirat_recurrentes) = "¿El adolescente  ha tenido infecciones respiratorias recurrentes (es decir, neumonía, gripe)?"
label(data$enf_medicamentos_cronicos) = "¿El adolescente ha usado medicamentos de forma crónica (por más de 3 meses)?"
label(data$enf_medicamentos_cronicos_si) = "Si marcó Sí, indique qué medicamentos usa o ha usado: "
label(data$hospita_previas) = "Durante este año, ¿El adolescente ha tenido hospitalizaciones previas?"
label(data$hospita_previas_1) = "Si marcó Sí, ¿Cuántas veces fue hospitalizado?"
label(data$hospita_previas_2) = "Si marcó Sí, ¿Por qué motivos fue hospitalizado? "
label(data$vacunas) = "Durante este año, ¿el adolescente tiene sus vacunas al día?"
label(data$vacunas_2) = "Si marcó Sí,  ¿Qué vacunas tiene actualmente?"
label(data$ant_familiar_pulmon) = "¿Algún familiar tiene diagnóstico de asma, rinitis o enfermedad pulmonar obstructiva crónica (EPOC)?"
label(data$ant_familiar_pulmon_2) = "Si marcó Sí, indiquie quién(es): "
label(data$ant_diabetes2) = "¿Algún familiar ha sido diagnosticado con diabetes tipo 2?"
label(data$ant_diabetes2_2) = "Si marcó Sí, indiquie quién(es): "
label(data$ant_hta) = "¿Algún familiar ha sido diagnosticado con hipertensión arterial?"
label(data$ant_hta_2) = "Si marcó Sí, indiquie quién(es): "
label(data$ant_fenf_cardiov) = "¿Algún familiar ha tenido enfermedad cardiovascular precoz (por ejemplo, infarto agudo de miocardio o accidente cerebrovascular antes de los 55 años en varones o 65 años en mujeres)?"
label(data$ant_fenf_cardiov_2) = "Si marcó Sí, indiquie quién(es): "
label(data$ant_dislipidemias) = "¿Algún familiar ha sido diagnosticado con dislipidemia (hipercolesterolemia, hipertrigliceridemia o ambas)?"
label(data$ant_dislipidemias_2) = "Si marcó Sí, indiquie quién(es): "
label(data$ant_cancer) = "¿Algún familiar ha tenido cáncer?"
label(data$ant_cancer_2) = "Si marcó Sí, indiquie quién(es): "
label(data$ant_obesidad) = "¿Algún familiar tiene obesidad o sobrepeso?"
label(data$ant_obesidad_2) = "Si marcó Sí, indiquie quién(es): "
label(data$ant_familiar_otros) = "¿Algún familiar tiene otras enfermedades (especifique:___________________________________________)?"
label(data$ant_familiar_otros_2) = "Si marcó Sí, indiquie quién(es): "
label(data$ansiedad_1) = "A. Ansiedad¿Con qué frecuencia se sintió nervioso(a), intranquilo(a) o con los nervios de punta?"
label(data$ansiedad_2) = "¿Con qué frecuencia sintió que no podía dejar de preocuparse o controlar la preocupación?"
label(data$depresion_1) = "B. Depresión:¿Con qué frecuencia tuvo poco interés o placer en hacer cosas?"
label(data$depresion_2) = "¿Con qué frecuencia se ha sentido decaído(a), deprimido(a) o sin esperanzas? "
label(data$cond_agresiv_1) = "A. Conductas dentro del hogar:¿Con qué frecuencia su hijo/a gritó a otros niños en casa?"
label(data$cond_agresiv_2) = "¿Con qué frecuencia su hijo(a) gritó a adultos en casa (por ejemplo, padres, cuidadores u otros familiares)?"
label(data$cond_agresiv_3) = "¿Con qué frecuencia su hijo(a) insultó a otros niños en casa?"
label(data$cond_agresiv_4) = "¿Con qué frecuencia su hijo(a) insultó a adultos en casa?"
label(data$cond_agresiv_5) = "¿Con qué frecuencia su hijo(a) amenazó verbalmente con golpear a un niño en casa?"
label(data$cond_agresiv_6) = "B. Conductas fuera del hogar:¿Con qué frecuencia su hijo(a) gritó a amigos o compañeros fuera de casa?"
label(data$cond_agresiv_7) = "¿Con qué frecuencia su hijo(a) gritó a adultos fuera de casa (por ejemplo, profesores, vecinos u otros adultos)?"
label(data$cond_agresiv_8) = "¿Con qué frecuencia su hijo(a) insultó a amigos o compañeros fuera de casa?"
label(data$cond_agresiv_9) = "¿Con qué frecuencia su hijo(a) insultó a adultos fuera de casa?"
label(data$encuestador_8) = "Encuestador"
label(data$fecha_hora_8) = "Fecha y hora (fin)"
label(data$comentario_antropometria_5) = "Comentario adicional"
label(data$cuestionario_padres_sociodemografico_complete) = "Complete?"
label(data$exposoma_1_1a) = "Duración (minutos) - a pie (caminando)"
label(data$exposoma_1_1b) = "Número de días en la semana - a pie (caminando)"
label(data$exposoma_1_2a) = "Duración (minutos) - en bicicleta"
label(data$exposoma_1_2b) = "Número de días en la semana - en bicicleta"
label(data$exposoma_1_3a) = "Duración (minutos) - en bus o en combi o metropolitano "
label(data$exposoma_1_3b) = "Número de días en la semana - en bus o en combi o metropolitano "
label(data$exposoma_1_4a) = "Duración (minutos) - en metro o tren"
label(data$exposoma_1_4b) = "Número de días en la semana - en metro o tren "
label(data$exposoma_1_5a) = "Duración (minutos) - en carro (auto propio, movilidad escolar, taxi o colectivo)"
label(data$exposoma_1_5b) = "Número de días en la semana - en carro (auto propio, movilidad escolar, taxi o colectivo) "
label(data$exposoma_1_6a) = "Duración (minutos) - en moto taxi o moto lineal"
label(data$exposoma_1_6b) = "Número de días en la semana - en moto taxi o moto lineal"
label(data$exposoma_2_1a) = "Duración (minutos) - a pie (caminando)"
label(data$exposoma_2_1b) = "Número de días en la semana - a pie (caminando)"
label(data$exposoma_2_2a) = "Duración (minutos) - en bicicleta"
label(data$exposoma_2_2b) = "Número de días en la semana - en bicicleta"
label(data$exposoma_2_3a) = "Duración (minutos) - en bus o en combi o metropolitano "
label(data$exposoma_2_3b) = "Número de días en la semana - en bus o en combi o metropolitano "
label(data$exposoma_2_4a) = "Duración (minutos) - en metro o tren"
label(data$exposoma_2_4b) = "Número de días en la semana - en metro o tren "
label(data$exposoma_2_5a) = "Duración (minutos) - en carro (auto propio, movilidad escolar, taxi o colectivo)"
label(data$exposoma_2_5b) = "Número de días en la semana - en carro (auto propio, movilidad escolar, taxi o colectivo) "
label(data$exposoma_2_6a) = "Duración (minutos) - en moto taxi o moto lineal"
label(data$exposoma_2_6b) = "Número de días en la semana - en moto taxi o moto lineal"
label(data$exposoma_3) = "Ayer, además del colegio o de su casa, ¿su hijo fue a algún otro lugar?(Por ejemplo: casa de un amigo o familiar, parque, centro comercial, mercado, iglesia, entrenamiento deportivo, etc.)."
label(data$exposoma_3_lugares_lugar_1) = "Cuántos lugares (1, 2, 3) marcó el familiares (choice=Lugar 1)"
label(data$exposoma_3_lugares_lugar_2) = "Cuántos lugares (1, 2, 3) marcó el familiares (choice=Lugar 2)"
label(data$exposoma_3_lugares_lugar_3) = "Cuántos lugares (1, 2, 3) marcó el familiares (choice=Lugar 3)"
label(data$exposoma_3_lugares_unknown) = "Cuántos lugares (1, 2, 3) marcó el familiares (choice=Unknown)"
label(data$exposoma_3_lugares_no_information) = "Cuántos lugares (1, 2, 3) marcó el familiares (choice=No information)"
label(data$exposoma_3_lugares_invalid) = "Cuántos lugares (1, 2, 3) marcó el familiares (choice=Invalid)"
label(data$exposoma_3_lugares_not_asked) = "Cuántos lugares (1, 2, 3) marcó el familiares (choice=Not asked)"
label(data$exposoma_3_lugar1_a) = "Nombre o tipo de lugar"
label(data$exposoma_3_lugar1_b) = "Nombre o tipo de lugar"
label(data$exposoma_3_lugar1_c) = "Distrito"
label(data$exposoma_3_lugar1_d) = "Modo de transporte (caminando, bus, combi, bicicleta, taxi) "
label(data$exposoma_3_lugar1_e) = "Tiempo total de viaje (ida y vuelta) "
label(data$exposoma_3_lugar2_a) = "Nombre o tipo de lugar"
label(data$exposoma_3_lugar2_b) = "Nombre o tipo de lugar"
label(data$exposoma_3_lugar2_c) = "Distrito"
label(data$exposoma_3_lugar2_d) = "Modo de transporte (caminando, bus, combi, bicicleta, taxi) "
label(data$exposoma_3_lugar2_e) = "Tiempo total de viaje (ida y vuelta) "
label(data$exposoma_3_lugar3_a) = "Nombre o tipo de lugar"
label(data$exposoma_3_lugar3_b) = "Nombre o tipo de lugar"
label(data$exposoma_3_lugar3_c) = "Distrito"
label(data$exposoma_3_lugar3_d) = "Modo de transporte (caminando, bus, combi, bicicleta, taxi) "
label(data$exposoma_3_lugar3_e) = "Tiempo total de viaje (ida y vuelta) "
label(data$exposoma_4) = "Durante el último mes, en promedio cuántas veces por semana (durante la semana)¿Cuántas veces jugó su hijo en espacios verdes?"
label(data$exposoma_5) = "Durante el último mes, en promedio cuántas veces por semana (durante el fin de semana)¿Cuántas veces jugó su hijo en espacios verdes?"
label(data$exposoma_6) = "Durante el último mes, en promedio cuántas horas por cada vez (durante la semana)¿Cuántas horas jugó su hijo en espacios verdes?"
label(data$exposoma_7) = "Durante el último mes, en promedio cuántas horas por cada vez (durante el fin de semana)¿Cuántas horas jugó su hijo en espacios verdes?"
label(data$exposoma_8) = "En el tiempo libre de su hijo/cuando no está en la escuela, ¿cuántas veces jugó su hijo en los espacios verdes hoy/ayer?"
label(data$exposoma_9) = "En el tiempo libre de su hijo/cuando no está en la escuela, ¿cuántas veces jugó su hijo en los espacios verdes en la última semana?"
label(data$exposoma_10) = "En el tiempo libre de su hijo/cuando no está en la escuela, ¿cuántas horas por cada vez jugó su hijo en los espacios verdes hoy/ayer?"
label(data$exposoma_11) = "En el tiempo libre de su hijo/cuando no está en la escuela, ¿cuántas horas por cada vez jugó su hijo en los espacios verdes en la última semana?"
label(data$exposoma_12_escuela_ref1) = "Nombre o referencia (año escolar, cuando hay clases)"
label(data$exposoma_12_escuela_ref2) = "Nombre o referencia (año escolar, cuando hay clases)"
label(data$exposoma_12_escuela_ref3) = "Nombre o referencia (año escolar, cuando hay clases)"
label(data$exposoma_12_escuela_dist1) = "Nombre o referencia (año escolar, cuando hay clases)"
label(data$exposoma_12_escuela_dist2) = "Nombre o referencia (año escolar, cuando hay clases)"
label(data$exposoma_12_escuela_dist3) = "Nombre o referencia (año escolar, cuando hay clases)"
label(data$exposoma_12_vacas_ref1) = "Nombre o referencia (año escolar, cuando hay clases)"
label(data$exposoma_12_vacas_ref2) = "Nombre o referencia (año escolar, cuando hay clases)"
label(data$exposoma_12_vacas_dist1) = "Nombre o referencia (año escolar, cuando hay clases)"
label(data$exposoma_12_vacas_dist2) = "Nombre o referencia (año escolar, cuando hay clases)"
label(data$exposoma_12_vacas_dist3) = "Nombre o referencia (año escolar, cuando hay clases)"
label(data$exposoma_13_1) = "Durante el año escolar: Bosque, montaña o río "
label(data$exposoma_13_2) = "Durante el año escolar: Playa"
label(data$exposoma_13_3) = "Durante las vacaciones: Bosque, montaña o río "
label(data$exposoma_13_4) = "Durante las vacaciones: Playa"
label(data$exposoma_13_5) = "Durante la última semana: Bosque, montaña o río "
label(data$exposoma_13_6) = "Durante la última semana: Playa"
label(data$exposoma_14_en_un_parque_o_area_verde_jardin_cerca_de_su_cas) = "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice=En un parque o área verde (jardín) cerca de su casa o barrio)"
label(data$exposoma_14_bosque_o_area_natural) = "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice=Bosque o área natural)"
label(data$exposoma_14_playa) = "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice=Playa)"
label(data$exposoma_14_patio_o_jardin_de_su_casa) = "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice=Patio o jardín de su casa)"
label(data$exposoma_14_en_otro_lugar) = "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice=En otro lugar)"
label(data$exposoma_14_unknown) = "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice=Unknown)"
label(data$exposoma_14_no_information) = "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice=No information)"
label(data$exposoma_14_invalid) = "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice=Invalid)"
label(data$exposoma_14_not_asked) = "Actividad reciente  Pensando en ayer o hoy, ¿su hijo pasó tiempo en alguno de los siguientes lugares? (choice=Not asked)"
label(data$exposoma_14_otro) = " En otro lugar (especifique): "
label(data$espacio_verde_seguro) = "En general, ¿cree que los espacios verdes cercanos a su casa  son seguros y adecuados para que los adolescentes jueguen?"
label(data$exposoma_15_1) = "Este barrio es un lugar en el que disfruto vivir"
label(data$exposoma_15_2) = "Es fácil obtener ayuda práctica de los vecinos"
label(data$exposoma_15_3) = "En mi barrio se puede confiar en la mayoría de las personas"
label(data$exposoma_16) = "¿Cuál de las siguientes opciones describe mejor su consumo de tabaco? (Responda usted, madre/padre/apoderado del adolescente)"
label(data$exposoma_17) = "¿Alguien fuma actualmente dentro de su casa?"
label(data$exposoma_17_1) = "¿Quién fuma dentro de su casa?"
label(data$exposoma_17_1_usted) = "Usted, ¿Cuántos cigarrillos fuma por semana en total?"
label(data$exposoma_17_1_usted1) = "Usted, ¿Cuántos de esos cigarrillos fuma dentro de la casa?"
label(data$exposoma_17_1_pareja) = "Su pareja, ¿Cuántos cigarrillos fuma por semana en total?"
label(data$exposoma_17_1_pareja1) = "Su pareja, ¿Cuántos de esos cigarrillos fuma dentro de la casa?"
label(data$exposoma_17_1_otra) = "Otra persona del hogar (por ejemplo, abuelo, tío, hermano), ¿Cuántos cigarrillos fuma por semana en total?"
label(data$exposoma_17_1_otra1) = "Otra persona del hogar (por ejemplo, abuelo, tío, hermano), ¿Cuántos de esos cigarrillos fuma dentro de la casa?"
label(data$exposoma_18) = "Durante la última semana, ¿su hijo estuvo en algún lugar cerrado donde alguien estaba fumando?"
label(data$exposoma_18_1) = "Si marcó sí, ¿cuántas veces por semana?"
label(data$exposoma_19) = "Presencia de industrias o empresas cercanas ¿Cerca de su casa (a menos de 100 metros) hay alguna empresa, taller o industria que emita humo, gases, polvo u olores fuertes? "
label(data$exposoma_20_fabrica_o_planta_industrial_ejemplo_cemento_alim) = "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice=Fábrica o planta industrial (ejemplo: cemento, alimentos, textiles, etc.))"
label(data$exposoma_20_taller_mecanico_o_de_soldadura) = "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice=Taller mecánico o de soldadura)"
label(data$exposoma_20_panaderia_o_polleria) = "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice=Panadería o polleria)"
label(data$exposoma_20_empresa_de_transporte_o_estacion_de_buses_camion) = "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice=Empresa de transporte o estación de buses/camiones)"
label(data$exposoma_20_otra_exposoma_20_otro) = "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice=Otra {exposoma_20_otro})"
label(data$exposoma_20_unknown) = "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice=Unknown)"
label(data$exposoma_20_no_information) = "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice=No information)"
label(data$exposoma_20_invalid) = "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice=Invalid)"
label(data$exposoma_20_not_asked) = "i. Identificación de las fuentes ¿Qué tipo de empresa o industria está más cerca de su casa?  (choice=Not asked)"
label(data$exposoma_20_otro) = "Especifique:"
label(data$exposoma_21) = "Aproximadamente, ¿A qué distancia se encuentra la empresa más cercana?"
label(data$exposoma_22) = "ii. Emisiones visibles ¿Ha visto usted que esta empresa o industria emite humo, polvo o gases hacia el aire? "
label(data$exposoma_23) = "¿Con qué frecuencia observa estas emisiones durante la semana?"
label(data$exposoma_24) = "¿A qué hora del día suele empezar la emisión de humo, gases o polvo? "
label(data$exposoma_25) = "¿Hasta qué hora aproximadamente continúan las emisiones?"
label(data$exposoma_26) = "iii. Características del humo o polvo Cuando ve el humo o el polvo, ¿de qué color suele ser principalmente? "
label(data$exposoma_26_otro) = "Otro color (especifique):"
label(data$exposoma_27) = "¿Ha notado algún olor fuerte o desagradable cuando se emiten estos humos o gases?"
label(data$exposoma_28) = "Si respondió Sí, ¿cómo describiría el olor? "
label(data$exposoma_28_otro) = "Otro (especifique):"
label(data$humo_impacto) = "iv. Percepción del impacto ¿Cree que estas emisiones podrían estar afectando la salud de su familia o de su hijo?"
label(data$encuestador_9) = "Encuestador"
label(data$fecha_hora_9) = "Fecha y hora (fin)"
label(data$comentario_exposoma_6) = "Comentario adicional"
label(data$cuestionario_de_padres_exposoma_complete) = "Complete?"
label(data$entorno_hogar_1) = "¿Cuántas personas viven en su vivienda?"
label(data$n_menor1) = "Menores de 1 año"
label(data$n_2a5) = "Entre 2 a 5 años"
label(data$n_6a17) = "Entre 6 a 17 años"
label(data$n_18a59) = "Entre 18 a 59 años"
label(data$n_mas60) = "60 años a más"
label(data$entorno_hogar_3) = "¿Cómo describiría dónde vive?"
label(data$entorno_hogar_3_otros) = "Especifique que otro tipo de vivienda:"
label(data$sala) = "Sala(s)"
label(data$dormitorio) = "Dormitorio(s)"
label(data$otros_ambientes) = "Otras ambientes (incluye cocina, baño(s)) "
label(data$sala_cortina) = "Sala: cortinas"
label(data$sala_alfombra_fija) = "Sala: alfombra fija (en el suelo)"
label(data$sala_tapete) = "Sala: tapete (que puede retirarse)"
label(data$dormitorio_hijo_cortina) = "Dormitorio de su hijo: cortinas"
label(data$dormitorio_hijo_alfombra) = "Dormitorio de su hijo: alfombra fija (en el suelo)"
label(data$dormitorio_hijo_tapete) = "Dormitorio de su hijo: tapete (que puede retirarse)"
label(data$bano_cortina) = "Baño(s): cortinas"
label(data$bano_alfombra) = "Baño(s): alfombra fija (en el suelo)"
label(data$bano_tapete) = "Baño(s): tapete (que puede retirarse)"
label(data$sala_veces_ano) = "Sala(s): veces al año que limpia"
label(data$dormitorio_veces_ano) = "Dormitorio de su hijo: veces al año que limpia"
label(data$bano_veces_ano) = "Baño(s): veces al año que limpia"
label(data$sala_forma_limpieza) = "Sala(s): forma principal de limpieza"
label(data$dormitorio_forma_limpieza) = "Dormitorio de su hijo: forma principal de limpieza"
label(data$bano_forma_limpieza) = "Baño(s): forma principal de limpieza"
label(data$entorno_hogar_7) = "¿De qué material principalmente están construidas las paredes exteriores de su casa/apartamento?"
label(data$entorno_hogar_7_otro) = "Otro (especifique):____________________________"
label(data$entorno_hogar_8_sala) = "Sala(s)"
label(data$entorno_hogar_8_dormitorio) = "Dormitorio del niño"
label(data$entorno_hogar_8_banos) = "Baño(s)"
label(data$entorno_hogar_9_frio) = "Temporada invierno/ frío"
label(data$entorno_hogar_9_calor) = "Temporada verano - primavera/ calor"
label(data$entorno_hogar_10) = "¿En qué medida le molesta la contaminación del aire al dejar las ventanas abiertas?(Se refiere a gases, humo, polvo del tráfico, industrias o quema de basura)"
label(data$entorno_hogar_11) = "¿Hacia dónde da la ventana del dormitorio de su hijo(a)?"
label(data$entorno_hogar_11_otros) = "Otra vista, especifique: _____________________________"
label(data$entorno_hogar_12_frio) = "Temporada invierno/ frío"
label(data$entorno_hogar_12_calor) = "Temporada verano - primavera/ calor"
label(data$entorno_hogar_13) = "¿En qué piso se encuentra el dormitorio de su hijo(a)? (Ejemplo: 0 = planta baja, 1 = primer piso, etc.)"
label(data$entorno_hogar_14) = "¿Cuántos pisos tiene en total su casa o edificio donde vive?"
label(data$entorno_hogar_15) = "¿Qué tipo de colchón usa su hijo(a)?"
label(data$entorno_hogar_15_otros) = "Otro (especifique): ___________________________________"
label(data$entorno_hogar_16) = "¿Qué edad aproximada tiene ese colchón?"
label(data$entorno_hogar_17) = "¿Tiene alguna mascota que viva principalmente dentro de la casa?"
label(data$entorno_hogar_17_gatos) = "Si respondió Sí, complete la siguiente información: ¿Usted tiene gatos?"
label(data$gato_1) = "¿Tiene gato(s)?"
label(data$gato_2) = "¿Duermen dentro de la casa?"
label(data$gato_3) = "¿Duermen en el mismo cuarto del niño(a)?"
label(data$gato_4) = "¿El gato vivía en la casa cuando nació su hijo(a)?"
label(data$gato_5) = "¿Cuántos gatos duermen dentro de la casa?"
label(data$gato_6) = "¿Cuántos duermen en el cuarto del niño(a)?"
label(data$gato_7) = "¿Hace cuánto convive el niño(a) con el gato/gatos? (años)"
label(data$gato_8) = "¿Hace cuánto convive el niño(a) con el gato/gatos? (meses)"
label(data$entorno_hogar_17_perros) = "¿Usted tiene perros?"
label(data$perro_1) = "¿Tiene perro(s)?"
label(data$perro_2) = "¿Duermen dentro de la casa?"
label(data$perro_3) = "¿Duermen en el mismo cuarto del niño(a)?"
label(data$perro_4) = "¿El perro vivía en la casa cuando nació su hijo(a)?"
label(data$perro_5) = "¿Cuántos perros duermen dentro de la casa?"
label(data$perro_6) = "¿Cuántos duermen en el cuarto del niño(a)?"
label(data$perro_7) = "¿Hace cuánto convive el niño(a) con el perro(s)? (años)"
label(data$perro_8) = "¿Hace cuánto convive el niño(a) con el perro(s)? (meses)"
label(data$entorno_hogar_17_aves) = "¿Usted tiene aves (pajaritos, loros, etc.)?"
label(data$ave_1) = "¿Tiene ave(s)?"
label(data$ave_2) = "¿Duermen dentro de la casa?"
label(data$ave_3) = "¿Duermen en el mismo cuarto del niño(a)?"
label(data$ave_4) = "¿La(s) ave(s) vivía en la casa cuando nació su hijo(a)?"
label(data$ave_5) = "¿Cuántos aves duermen dentro de la casa?"
label(data$ave_6) = "¿Cuántos duermen en el cuarto del niño(a)?"
label(data$ave_7) = "¿Hace cuánto convive el niño(a) con el ave(s)? (años)"
label(data$ave_8) = "¿Hace cuánto convive el niño(a) con el ave(s)? (meses)"
label(data$entorno_hogar_17_corral) = "¿Usted tiene animal de corral (palomas, gallinas, cuyes, etc.)?"
label(data$corral_1) = "¿Tiene  animal(es) de corral (palomas, gallinas, cuyes, etc.)?"
label(data$corral_2) = "¿Duermen dentro de la casa?"
label(data$corral_3) = "¿Duermen en el mismo cuarto del niño(a)?"
label(data$corral_4) = "¿Los animales de corral (palomas, gallinas, cuyes, etc.) vivían en la casa cuando nació su hijo(a)?"
label(data$corral_5) = "¿Cuántos  animales de corral (palomas, gallinas, cuyes, etc.) duermen dentro de la casa?"
label(data$corral_6) = "¿Cuántos duermen en el cuarto del niño(a)?"
label(data$corral_7) = "¿Hace cuánto convive el niño(a) con los animales de corral (palomas, gallinas, cuyes, etc.)? (años)"
label(data$corral_8) = "¿Hace cuánto convive el niño(a) con los animales de corral (palomas, gallinas, cuyes, etc.)? (meses)"
label(data$entorno_hogar_18_roedores) = "Roedores"
label(data$entorno_cucarachas_18) = "Cucarachas"
label(data$entorno_hogar_19) = "¿Considera que su casa está húmeda?"
label(data$entorno_hogar_20) = "¿Hay moho o manchas de moho dentro de su casa (excepto en los alimentos)?"
label(data$entorno_hogar_20_moho_1) = "Habitación del niño(a)"
label(data$entorno_hogar_20_moho_2) = "Resto de la casa"
label(data$entorno_hogar_20_moho_3) = "Baño(s)"
label(data$entorno_hogar_20_moho_4) = "Cocina"
label(data$entorno_hogar_20_moho_5) = "Sótano / depósito"
label(data$entorno_hogar_22) = "La casa donde vive actualmente su hijo(a), ¿es la misma donde usted vivía cuando estaba embarazada?"
label(data$entorno_hogar_23_1) = "Distrito, departamento (desde el embarazo)"
label(data$entorno_hogar_23_1_1) = "Dirección o referencia (desde el embarazo)"
label(data$entorno_hogar_23_1_2) = "Tiempo vivido, en años (desde el embarazo)"
label(data$entorno_hogar_23_2) = "Distrito, departamento (0 a 2 años)"
label(data$entorno_hogar_23_2_1) = "Dirección o referencia (0 a 2 años)"
label(data$entorno_hogar_23_2_2) = "Tiempo vivido, en años (0 a 2)"
label(data$entorno_hogar_23_3) = "Distrito, departamento (3 a 5 años)"
label(data$entorno_hogar_23_3_1) = "Dirección o referencia (3 a 5 años)"
label(data$entorno_hogar_23_3_2) = "Tiempo vivido, en años (3 a 5)"
label(data$entorno_hogar_23_4) = "Distrito, departamento (6 a 10 años)"
label(data$entorno_hogar_23_4_1) = "Dirección o referencia (6 a 10 años)"
label(data$entorno_hogar_23_4_2) = "Tiempo vivido, en años (6 a 10)"
label(data$entorno_hogar_23_5) = "Distrito, departamento (actual)"
label(data$entorno_hogar_23_5_1) = "Dirección o referencia (actual)"
label(data$entorno_hogar_23_5_2) = "Tiempo vivido, en años (actual)"
label(data$entorno_hogar_24) = "¿Existen edificaciones o vías en construcción, o calles sin pavimentar, a menos de una cuadra (100 metros) de su casa?"
label(data$entorno_hogar_25) = "¿Existen fábricas, talleres o negocios cerca de su casa (a menos de una cuadra o 100 metros) Como: ladrilleras, madereras, calderas, quemas de llantas o basura, ¿talleres con humo o polvo?"
label(data$entorno_hogar_26) = "Mientras su hijo(a) ha vivido en esta casa, ¿se han realizado obras, ampliaciones o remodelaciones Como: construcción, pintura, cambio de techo, pisos o paredes"
label(data$entorno_hogar_27) = "¿La cocina está ubicada dentro del ambiente principal de la vivienda o en una zona exterior?"
label(data$entorno_hogar_28) = "¿Su cocina cuenta con un extractor o campana de aire encima de la cocina?"
label(data$entorno_hogar_29) = "Cuando cocina, ¿con qué frecuencia utiliza el extractor o campana de aire?"
label(data$entorno_hogar_30) = "¿Qué tipo de cocina o estufa usa principalmente en su hogar? "
label(data$entorno_hogar_30_1) = "Otro, especificar"
label(data$entorno_hogar_31) = "¿Cuántas veces a la semana cocina utilizando una sartén antiadherente (teflón)?"
label(data$entorno_hogar_32_1) = "Lejía/blanqueador"
label(data$entorno_hogar_32_2) = "Amoníaco"
label(data$entorno_hogar_32_3) = "Solvente quitamanchas"
label(data$entorno_hogar_32_4) = "Limpiador de muebles"
label(data$entorno_hogar_32_5) = "Limpiavidrios"
label(data$entorno_hogar_32_6) = "Spray para alfombras, mantas o cortinas"
label(data$entorno_hogar_32_7) = "Limpiador aromatizado de pisos"
label(data$entorno_hogar_32_8) = "Limpiador de hornos o cocina"
label(data$entorno_hogar_32_9) = "Ambientadores (en spray o eléctricos)"
label(data$entorno_hogar_32_10) = "Spray para planchar ropa"
label(data$entorno_hogar_32_11) = "Productos de limpieza perfumados"
label(data$entorno_hogar_32_12) = "Limpiadores líquidos multiusos"
label(data$entorno_hogar_32_13) = "Bolas de naftalina o similares"
label(data$entorno_hogar_32_14) = "Aerosoles desengrasantes"
label(data$entorno_hogar_32_15) = "Otros productos de limpieza (especifique):"
label(data$entorno_hogar_32_otro) = "Otros productos de limpieza (especifique): "
label(data$entorno_hogar_33) = "¿Con qué frecuencia limpia la vivienda (barrer, trapear, quitar polvo, etc.)?"
label(data$entorno_hogar_34) = "¿Tienen aspiradora en su hogar?"
label(data$entorno_hogar_35) = "Si tiene aspiradora, ¿esta cuenta con un filtro HEPA o de alta eficiencia?"
label(data$entorno_hogar_36) = "¿Con qué frecuencia aspiran su vivienda?"
label(data$encuestador_10) = "Encuestador"
label(data$fecha_hora_10) = "Fecha y hora (fin)"
label(data$comentario_antropometria_7) = "Comentario adicional"
label(data$cuestionario_de_padres_informacin_sobre_el_ambient_complete) = "Complete?"
label(data$presion_sistolica_padre_1) = "Presión arterial sistólica (Primera toma)"
label(data$presion_diastolica_padre_1) = "Presión arterial diastólica (Primera toma)"
label(data$presion_sistolica_padre_2) = "Presión arterial sistólica (segunda toma)"
label(data$presion_diastolica_padre_2) = "Presión arterial sistólica (segunda toma)"
label(data$peso_padre) = "Peso"
label(data$talla_padre_2) = "Talla"
label(data$pcintura_padre) = "Perímetro de cintura"
label(data$encuestador_11) = "Encuestador"
label(data$fecha_hora_11) = "Fecha y hora (fin)"
label(data$comentario_antropometria_8) = "Comentario adicional"
label(data$cuestionario_de_padres_cartilla_clnica_de_los_padr_complete) = "Complete?"
label(data$desayuno_biomarcadores) = "¿El niño(a) desayunó antes de la recolección de la muestra de biomarcadores?"
label(data$colesterol_total) = "Perfil lipídico: Colesterol total"
label(data$hdl_colesterol) = "Perfil lipídico:HDL-colesterol (HDL-c)"
label(data$trigliceridos) = "Perfil lipídico: Triglicéridos"
label(data$glucosa) = "Glucosa"
label(data$encuestador_biomarcadores) = "Encuestador"
label(data$fecha_hora_biomarcadores) = "Fecha y hora (fin)"
label(data$comentario_biomarcadores) = "Comentario adicional"
label(data$cuestionario_adolescentes_biomarcadores_complete) = "Complete?"
label(data$alergia_pteronyssinus) = "¿El niño(a) presentó reacción alérgica al ácaro del polvo Dermatophagoides pteronyssinus?"
label(data$alergia_farinae) = "¿El niño(a) presentó reacción alérgica al ácaro del polvo Dermatophagoides farinae?"
label(data$alergia_destructor) = "¿El niño(a) presentó reacción alérgica al ácaro Lepidoglyphus destructor?"
label(data$alergia_tropicalis) = "¿El niño(a) presentó reacción alérgica al ácaro Blomia tropicalis?"
label(data$alergia_arcuatus) = "¿El niño(a) presentó reacción alérgica al ácaro Chortoglyphus arcuatus?"
label(data$alergia_alternata) = "¿El niño(a) presentó reacción alérgica al moho Alternaria alternata?"
label(data$alergia_herbarum) = "¿El niño(a) presentó reacción alérgica al moho Cladosporium herbarum?"
label(data$alergia_fumigatus) = "¿El niño(a) presentó reacción alérgica al moho Aspergillus fumigatus?"
label(data$alergia_notatum) = "¿El niño(a) presentó sensibilización al moho Penicillium notatum?"
label(data$alergia_grasses) = "¿El niño(a) presentó reacción alérgica a la mezcla de grasses?"
label(data$alergia_vulgaris) = "¿El niño(a) presentó reacción alérgica a la Artemisia vulgaris?"
label(data$alergia_ambrosia) = "¿El niño(a) presentó reacción alérgica a la Ambrosia?"
label(data$alergia_perro) = "¿El niño(a) presentó reacción alérgica al epitelio de perro?"
label(data$alergia_gato) = "¿El niño(a) presentó reacción alérgica al epitelio de gato?"
label(data$alergia_germanica) = "¿El niño(a) presentó reacción alérgica a la cucaracha Blattella germanica?"
label(data$alergia_americana) = "¿El niño(a) presentó reacción alérgica a la cucaracha Periplaneta americana?"
label(data$alergia_olivo) = "¿El niño(a) presentó reacción alérgica al Olivo?"
label(data$asma) = "¿Usted tiene asma?"
label(data$severidad_asma) = "¿Qué severidad tiene su asma? (Para ser llenado por médico)"
label(data$rinitis_alergica) = "¿Usted tiene rinitis alérgica?"
label(data$severidad_rinitis) = "¿Qué severidad tiene su rinitis? (Para ser llenado por médico)"
label(data$sintomas_respiratorios_acaros_del_polvo_polvo_casero) = "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice=Ácaros del polvo (polvo casero))"
label(data$sintomas_respiratorios_hongos_o_moho) = "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice=Hongos o moho)"
label(data$sintomas_respiratorios_pelo_o_caspa_de_mascotas_perros_gatos) = "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice=Pelo o caspa de mascotas (perros, gatos, etc.))"
label(data$sintomas_respiratorios_polenes_de_arboles_plantas_o_flores) = "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice=Pólenes de árboles, plantas o flores)"
label(data$sintomas_respiratorios_ninguno_de_los_anteriores) = "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice=Ninguno de los anteriores)"
label(data$sintomas_respiratorios_unknown) = "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice=Unknown)"
label(data$sintomas_respiratorios_no_information) = "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice=No information)"
label(data$sintomas_respiratorios_invalid) = "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice=Invalid)"
label(data$sintomas_respiratorios_not_asked) = "Sus síntomas respiratorios incrementan cuando se expone a ...............(Para ser llenado por médico) (choice=Not asked)"
label(data$isaac_asma_21) = "¿Alguna vez has tenido silbidos o pitos en el pecho en el pasado?Si ha contestado NO, por favor salte a la pregunta ¿Algún médico te ha diagnosticado asma?"
label(data$isaac_asma_22) = "En los últimos 12 meses, ¿has tenido silbidos o pitidos en el pecho?Si ha contestado NO, por favor salte a la pregunta ¿Algún médico te ha diagnosticado asma?"
label(data$isaac_asma_23) = "¿Cuántos ataques de silbidos has tenido en los últimos 12 meses?"
label(data$isaac_asma_24) = "En los últimos 12 meses, ¿cuántas noches por semana, en promedio, te ha despertado la sibilancia?"
label(data$isaac_asma_25) = "En los últimos 12 meses, ¿la sibilancia ha limitado alguna vez tu habla a menos de una frase completa?"
label(data$isaac_asma_26) = "¿Algún médico te ha diagnosticado asma?"
label(data$isaac_asma_27) = "En los últimos 12 meses, ¿has tenido silbidos asociados al ejercicio físico (durante la práctica de deporte)?"
label(data$isaac_asma_28) = "En los últimos 12 meses, ¿has tenido una tos seca nocturna sin estar resfriado o teniendo gripe?"
label(data$isaac_rinitis_29) = "¿Alguna vez has tenido un problema nasal (estornudos, goteo o congestión nasal) sin estar resfriado o con gripe? Si ha contestado NO, por favor salte a la pregunta ¿Un médico te ha diagnosticado rinitis alérgica (alergia nasal)?"
label(data$isaac_rinitis_30) = "¿En los últimos 12 meses has tenido un problema nasal (estornudos, goteo o congestión nasal) sin estar resfriado o con gripe? Si ha contestado NO, por favor salte a la pregunta ¿Un médico te ha diagnosticado rinitis alérgica (alergia nasal)?"
label(data$isaac_rinitis_31) = "¿Cuántos meses al año, aproximadamente, suele afectarte este problema nasal?"
label(data$isaac_rinitis_32) = "¿Estos síntomas nasales, durante los últimos 12 meses, han limitado tu actividad normal (jugar, ir a la escuela, hacer deporte)?"
label(data$isaac_rinitis_33) = "¿Has tenido comezón y lagrimeo ocular junto con los síntomas nasales en los últimos 12 meses?"
label(data$isaac_rinitis_34) = "¿Un médico te ha diagnosticado rinitis alérgica (alergia nasal)?"
label(data$isaac_dermatitis_35) = "¿Alguna vez has tenido erupción de picor que haya durado más de una semana? Si ha contestado NO, por favor salte a la pregunta ¿Un médico te ha diagnosticado eczema o dermatitis atópica?"
label(data$isaac_dermatitis_36) = "¿En los últimos 12 meses has tenido una erupción de picor? Si ha contestado NO, por favor salte a la pregunta ¿Un médico te ha diagnosticado eczema o dermatitis atópica?"
label(data$isaac_dermatitis_37) = "¿En los últimos 12 meses, has tenido esa erupción de picor en alguno de estos sitios: dentro de los codos, detrás de las rodillas, al frente de los tobillos, bajo las nalgas, alrededor del cuello, ¿los ojos u orejas?"
label(data$isaac_dermatitis_38) = "¿En los últimos 12 meses, ¿la erupción ha desaparecido completamente durante algún período?"
label(data$isaac_dermatitis_39) = "¿La erupción de picor ha afectado tu sueño en los últimos 12 meses? Si es así, ¿con qué frecuencia?"
label(data$isaac_dermatitis_40) = "¿Un médico te ha diagnosticado eczema o dermatitis atópica?"
label(data$feno) = "FENORegistrar el valor de la fracción exhalada de óxido nítrico (FeNO) obtenido con el dispositivo calibrado"
label(data$encuestador_alergias) = "Encuestador"
label(data$fecha_hora_alergias) = "Fecha y hora (fin)"
label(data$comentario_alergias) = "Comentario adicional"
label(data$cuestionario_adolescentes_alergias_complete) = "Complete?"
label(data$peso_1) = "Peso - Toma 1"
label(data$peso_2) = "Peso - Toma 2"
label(data$peso_3) = "Peso - Toma 3"
label(data$talla_1) = "Talla - Toma 1"
label(data$talla_2) = "Talla - Toma 2"
label(data$talla_3) = "Talla - Toma 3"
label(data$talla_sentado_1) = "Talla sentado - Toma 1"
label(data$talla_sentado_2) = "Talla sentado - Toma 2"
label(data$talla_sentado_3) = "Talla sentado - Toma 3"
label(data$pliegue_bicipital_1) = "Pliegue bicipital - Toma 1"
label(data$pliegue_bicipital_2) = "Pliegue bicipital - Toma 2"
label(data$pliegue_bicipital_3) = "Pliegue bicipital - Toma 3"
label(data$pliegue_triceps_1) = "Pliegue tricipital - Toma 1"
label(data$pliegue_triceps_2) = "Pliegue tricipital - Toma 2"
label(data$pliegue_triceps_3) = "Pliegue tricipital - Toma 3"
label(data$pliegue_subescapular_1) = "Pliegue subescapular - Toma 1"
label(data$pliegue_subescapular_2) = "Pliegue subescapular - Toma 2"
label(data$pliegue_subescapular_3) = "Pliegue subescapular - Toma 3"
label(data$pliegue_pierna_1) = "Pliegue de pierna - Toma 1"
label(data$pliegue_pierna_2) = "Pliegue de pierna - Toma 2"
label(data$pliegue_pierna_3) = "Pliegue de pierna - Toma 3"
label(data$perimetro_cuello_1) = "Perímetro de cuello - Toma 1"
label(data$perimetro_cuello_2) = "Perímetro de cuello - Toma 2"
label(data$perimetro_cuello_3) = "Perímetro de cuello - Toma 3"
label(data$perimetro_cintura_1) = "Perímetro de cintura - Toma 1"
label(data$perimetro_cintura_2) = "Perímetro de cintura - Toma 2"
label(data$perimetro_cintura_3) = "Perímetro de cintura - Toma 3"
label(data$perimetro_cadera_1) = "Perímetro de cadera - Toma 1"
label(data$perimetro_cadera_2) = "Perímetro de cadera - Toma 2"
label(data$perimetro_cadera_3) = "Perímetro de cadera - Toma 3"
label(data$masa_grasa_corporal) = "Porcentaje de masa grasa corporal (bioimpedancia)"
label(data$grasa_visceral) = "Porcentaje de grasa visceral (bioimpedancia)"
label(data$vo2max_fc_final) = "Frecuencia cardíaca final: Frecuencia cardíaca al finalizar los 3 minutos (bpm)"
label(data$vo2max_sato2) = "Saturación de oxígeno: Saturación de oxígeno al finalizar los 3 minutos (SaO₂ %)"
label(data$dinamo_1) = "Dinamómetro - Toma 1"
label(data$dinamo_2) = "Dinamómetro - Toma 2"
label(data$dinamo_3) = "Dinamómetro - Toma 3"
label(data$dinamo_max) = "Mejor fuerza (valor máximo)"
label(data$encuestador_antropometria) = "Encuestador"
label(data$fecha_hora_antropometria) = "Fecha y hora (fin)"
label(data$comentario_antropometria) = "Comentario adicional"
label(data$cuestionario_adolescentes_antropometria_complete) = "Complete?"
label(data$pas_1) = "Presión arterial sistólica (PAS) - Toma 1"
label(data$pas_2) = "Presión arterial sistólica (PAS) - Toma 2"
label(data$pas_3) = "Presión arterial sistólica (PAS) - Toma 3"
label(data$pad_1) = "Presión arterial diastólica (PAD) - Toma 1"
label(data$pad_2) = "Presión arterial diastólica (PAD) - Toma 2"
label(data$pad_3) = "Presión arterial diastólica (PAD) - Toma 3"
label(data$pulso_1) = "Frecuencia cardiaca (pulso) - Toma 1"
label(data$pulso_2) = "Frecuencia cardiaca (pulso) - Toma 2"
label(data$pulso_3) = "Frecuencia cardiaca (pulso) - Toma 3"
label(data$encuestador_parterial) = "Encuestador"
label(data$fecha_hora_parterial) = "Fecha y hora (fin)"
label(data$comentario_parterial) = "Comentario adicional"
label(data$cuestionario_adolescentes_presion_arterial_complete) = "Complete?"
label(data$sintomas_depresivos_1) = "¿Te has sentido deprimido(a), irritable o sin esperanza?"
label(data$sintomas_depresivos_2) = "¿Has tenido poco interés o placer en hacer cosas?"
label(data$sintomas_depresivos_3) = "¿Has tenido dificultad para dormirte, mantenerte dormido(a) o has dormido demasiado?"
label(data$sintomas_depresivos_4) = "¿Has tenido poco apetito, pérdida de peso o has comido en exceso?"
label(data$sintomas_depresivos_5) = "¿Te has sentido cansado(a) o con poca energía?"
label(data$sintomas_depresivos_6) = "¿Has sentido que has fallado a tu familia o a ti mismo(a)?"
label(data$sintomas_depresivos_7) = "¿Has tenido problemas para concentrarte en tareas escolares, leer o ver televisión?"
label(data$sintomas_depresivos_8) = "¿Te has movido o hablado tan lentamente que otras personas lo notan? ¿O has estado inquieto(a), moviéndote más de lo usual?"
label(data$sintomas_depresivos_9) = "¿Has tenido pensamientos de que estarías mejor muerto(a) o de hacerte daño de alguna manera?"
label(data$sintomas_ansiedad_1) = "Sentí momentos de terror, miedo o susto repentino."
label(data$sintomas_ansiedad_2) = "Me sentí ansioso(a), preocupado(a) o nervioso(a)."
label(data$sintomas_ansiedad_3) = "Tuve pensamientos sobre cosas malas que podrían pasar, como una tragedia familiar, enfermedad, pérdida de trabajo o accidentes."
label(data$sintomas_ansiedad_4) = "Sentí el corazón acelerado, sudoración, dificultad para respirar, mareo o temblores."
label(data$sintomas_ansiedad_5) = "Sentí los músculos tensos, estaba inquieto(a) o con dificultad para relajarme o dormir."
label(data$sintomas_ansiedad_6) = "Evité o no me acerqué a situaciones que me causaban preocupación."
label(data$sintomas_ansiedad_7) = "Me retiré temprano de situaciones o participé muy poco debido a mis preocupaciones."
label(data$sintomas_ansiedad_8) = "Pasé mucho tiempo tomando decisiones, postergando decisiones o preparándome para situaciones por mis preocupaciones."
label(data$sintomas_ansiedad_9) = "Busqué tranquilidad o confirmación de otras personas debido a mis preocupaciones."
label(data$sintomas_ansiedad_10) = "Necesité ayuda para sobrellevar mi ansiedad (por ejemplo, alcohol, medicación, objetos supersticiosos o apoyo de otras personas)."
label(data$nutricion_1) = "Cuando almuerzo fuera de casa, suelo elegir una opción baja en grasa."
label(data$nutricion_2) = "Suelo evitar comer frituras."
label(data$nutricion_3) = "Suelo comer postres si hay disponibles."
label(data$nutricion_4) = "Me aseguro de comer al menos una porción de fruta al día."
label(data$nutricion_5) = "Trato de mantener bajo mi consumo total de grasa."
label(data$nutricion_6) = "Si compro papas fritas (snacks), elijo una marca baja en grasa."
label(data$nutricion_7) = "Evito comer muchas salchichas y hamburguesas."
label(data$nutricion_8) = "Suelo comprar dulces o tortas."
label(data$nutricion_9) = "Trato de mantener bajo mi consumo total de azúcar."
label(data$nutricion_10) = "Como al menos una porción de verduras o ensalada al día."
label(data$nutricion_11) = "Si como postre en casa, intento que sea bajo en grasa."
label(data$nutricion_12) = "Rara vez como comida para llevar."
label(data$nutricion_13) = "Trato de comer muchas frutas y verduras."
label(data$nutricion_14) = "Suelo comer dulces o snacks entre comidas."
label(data$nutricion_15) = "Generalmente como al menos una porción de verduras (sin contar papas) o ensalada por la noche."
label(data$nutricion_16) = "Cuando compro una bebida gaseosa, elijo una versión dietética."
label(data$nutricion_17) = "Cuando pongo mantequilla/margarina en el pan, uso una capa delgada."
label(data$nutricion_18) = "Si llevo lonchera, normalmente incluyo chocolate o galletas."
label(data$nutricion_19) = "Si como un snack entre comidas, suelo elegir fruta."
label(data$nutricion_20) = "Si como postre en un restaurante, elijo el más saludable disponible."
label(data$nutricion_21) = "Suelo poner crema a los postres."
label(data$nutricion_22) = "Como al menos tres porciones de fruta la mayoría de días."
label(data$nutricion_23) = "En general, trato de llevar una dieta saludable."
label(data$paqc_1) = "Durante los últimos 7 días, en tus clases de educación física, ¿con qué frecuencia estuviste muy activo(a)?"
label(data$paqc_2) = "Durante los últimos 7 días, ¿qué hiciste durante el recreo?"
label(data$paqc_3) = "Durante los últimos 7 días, ¿qué hiciste en la hora de almuerzo (además de comer)?"
label(data$paqc_4) = "Durante los últimos 7 días, inmediatamente después del colegio ¿cuántos días practicaste deporte, bailaste o jugaste en los que estuvieras muy activo? "
label(data$paqc_5) = "Durante los últimos 7 días, ¿en cuántas noches hiciste deporte, bailaste o jugaste activamente? "
label(data$paqc_6) = "Durante el último fin de semana, ¿cuántas veces hiciste deporte, bailaste o jugaste activamente? "
label(data$paqc_7) = "¿Cuál de las siguientes opciones te describe mejor en los últimos 7 días?"
label(data$paqc_8_1_ninguna) = "Lunes (choice=Ninguna)"
label(data$paqc_8_1_a_veces) = "Lunes (choice=A veces)"
label(data$paqc_8_1_regular) = "Lunes (choice=Regular)"
label(data$paqc_8_1_frecuente) = "Lunes (choice=Frecuente)"
label(data$paqc_8_1_muy_frecuente) = "Lunes (choice=Muy frecuente)"
label(data$paqc_8_1_unknown) = "Lunes (choice=Unknown)"
label(data$paqc_8_1_no_information) = "Lunes (choice=No information)"
label(data$paqc_8_1_invalid) = "Lunes (choice=Invalid)"
label(data$paqc_8_1_not_asked) = "Lunes (choice=Not asked)"
label(data$paqc_8_2_ninguna) = "Martes (choice=Ninguna)"
label(data$paqc_8_2_a_veces) = "Martes (choice=A veces)"
label(data$paqc_8_2_regular) = "Martes (choice=Regular)"
label(data$paqc_8_2_frecuente) = "Martes (choice=Frecuente)"
label(data$paqc_8_2_muy_frecuente) = "Martes (choice=Muy frecuente)"
label(data$paqc_8_2_unknown) = "Martes (choice=Unknown)"
label(data$paqc_8_2_no_information) = "Martes (choice=No information)"
label(data$paqc_8_2_invalid) = "Martes (choice=Invalid)"
label(data$paqc_8_2_not_asked) = "Martes (choice=Not asked)"
label(data$paqc_8_3_ninguna) = "Miércoles (choice=Ninguna)"
label(data$paqc_8_3_a_veces) = "Miércoles (choice=A veces)"
label(data$paqc_8_3_regular) = "Miércoles (choice=Regular)"
label(data$paqc_8_3_frecuente) = "Miércoles (choice=Frecuente)"
label(data$paqc_8_3_muy_frecuente) = "Miércoles (choice=Muy frecuente)"
label(data$paqc_8_3_unknown) = "Miércoles (choice=Unknown)"
label(data$paqc_8_3_no_information) = "Miércoles (choice=No information)"
label(data$paqc_8_3_invalid) = "Miércoles (choice=Invalid)"
label(data$paqc_8_3_not_asked) = "Miércoles (choice=Not asked)"
label(data$paqc_8_4_ninguna) = "Jueves (choice=Ninguna)"
label(data$paqc_8_4_a_veces) = "Jueves (choice=A veces)"
label(data$paqc_8_4_regular) = "Jueves (choice=Regular)"
label(data$paqc_8_4_frecuente) = "Jueves (choice=Frecuente)"
label(data$paqc_8_4_muy_frecuente) = "Jueves (choice=Muy frecuente)"
label(data$paqc_8_4_unknown) = "Jueves (choice=Unknown)"
label(data$paqc_8_4_no_information) = "Jueves (choice=No information)"
label(data$paqc_8_4_invalid) = "Jueves (choice=Invalid)"
label(data$paqc_8_4_not_asked) = "Jueves (choice=Not asked)"
label(data$paqc_8_5_ninguna) = "Viernes (choice=Ninguna)"
label(data$paqc_8_5_a_veces) = "Viernes (choice=A veces)"
label(data$paqc_8_5_regular) = "Viernes (choice=Regular)"
label(data$paqc_8_5_frecuente) = "Viernes (choice=Frecuente)"
label(data$paqc_8_5_muy_frecuente4) = "Viernes (choice=Muy frecuente)"
label(data$paqc_8_5_unknown) = "Viernes (choice=Unknown)"
label(data$paqc_8_5_no_information) = "Viernes (choice=No information)"
label(data$paqc_8_5_invalid) = "Viernes (choice=Invalid)"
label(data$paqc_8_5_not_asked) = "Viernes (choice=Not asked)"
label(data$paqc_8_6_ninguna) = "Sábado (choice=Ninguna)"
label(data$paqc_8_6_a_veces) = "Sábado (choice=A veces)"
label(data$paqc_8_6_regular) = "Sábado (choice=Regular)"
label(data$paqc_8_6_frecuente) = "Sábado (choice=Frecuente)"
label(data$paqc_8_6_muy_frecuente) = "Sábado (choice=Muy frecuente)"
label(data$paqc_8_6_unknown) = "Sábado (choice=Unknown)"
label(data$paqc_8_6_no_information) = "Sábado (choice=No information)"
label(data$paqc_8_6_invalid) = "Sábado (choice=Invalid)"
label(data$paqc_8_6_not_asked) = "Sábado (choice=Not asked)"
label(data$paqc_8_7_ninguna) = "Domingo (choice=Ninguna)"
label(data$paqc_8_7_a_veces) = "Domingo (choice=A veces)"
label(data$paqc_8_7_regular) = "Domingo (choice=Regular)"
label(data$paqc_8_7_frecuente) = "Domingo (choice=Frecuente)"
label(data$paqc_8_7_muy_frecuente) = "Domingo (choice=Muy frecuente)"
label(data$paqc_8_7_unknown) = "Domingo (choice=Unknown)"
label(data$paqc_8_7_no_information) = "Domingo (choice=No information)"
label(data$paqc_8_7_invalid) = "Domingo (choice=Invalid)"
label(data$paqc_8_7_not_asked) = "Domingo (choice=Not asked)"
label(data$paqc_9) = "¿Estuviste enfermo(a) esta última semana o algo impidió que hicieras normalmente actividad física?"
label(data$paqc_9_1) = "Si marcó sí, especifique el motivo de enfermedad:"
label(data$encuestador_saludmental) = "Encuestador"
label(data$fecha_hora_saludmental) = "Fecha y hora (fin)"
label(data$comentario_saludmental) = "Comentario adicional"
label(data$cuestionario_adolescentes_salud_mental_complete) = "Complete?"
label(data$presion_atm) = "Presión atmosférica"
label(data$temperatura_ambiente) = "Temperatura ambiente"
label(data$humedad) = "Humedad relativa"
label(data$altitud) = "Altitud"
label(data$cirujia) = "¿Cirugía de ojo, corazón, pecho, pulmón, o abdominal en los últimos 3 meses?"
label(data$ataque_corazon) = "¿Un ataque al corazón en los últimos 3 meses?"
label(data$presion_espirometria) = "¿Presión arterial mayor que 180 (sistólico) / 120 (diastólico)?"
label(data$pulso_espirometria) = "¿Pulso mayor que 120 latidos/min?"
label(data$infeccion_respiratoria) = "¿Infección respiratoria en las últimas 2 semanas?"
label(data$broncodilatador_12h) = "¿Broncodilatador de acción prolongada en las últimas 12 horas?"
label(data$broncodilatador_4h) = "¿Broncodilatador de acción corta en las últimas 4 horas?"
label(data$fumo) = "¿Fumó en la última hora?"
label(data$fiebre) = "Fiebre"
label(data$tos) = "Tos"
label(data$dolor_garganta) = "Dolor de garganta"
label(data$flema) = "Flema"
label(data$escalofrios) = "Escalofríos"
label(data$dolor_cuerpo) = "Dolor de cuerpo"
label(data$fatiga) = "Fatiga"
label(data$dolor_cabeza) = "Dolor de cabeza"
label(data$congestion) = "Congestión nasal"
label(data$goteo) = "Goteo de nariz"
label(data$estornudos) = "Estornudos"
label(data$id_espirometro) = "ID de espirómetro"
label(data$espirometria) = "¿Realizada?"
label(data$fvc) = "Capacidad vital forzada (CVF o FVC)"
label(data$fev1) = "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
label(data$fev1_fvc) = "FEV1/FVC"
label(data$pef) = "Flujo espiratorio máximo (PEF o FEF)"
label(data$fev3) = "Volumen espiratorio forzado en tres segundos (FEV3)"
label(data$fev6) = "Volumen espiratorio forzado en seis segundos (FEV6)"
label(data$error_espirometria) = "Error"
label(data$espirometria_aceptable) = "¿Aceptable?"
label(data$espirometria_2) = "¿Realizada?"
label(data$fvc_2) = "Capacidad vital forzada (CVF o FVC)"
label(data$fev1_2) = "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
label(data$fev1_fvc_2) = "FEV1/FVC"
label(data$pef_2) = "Flujo espiratorio máximo (PEF o FEF)"
label(data$fev3_2) = "Volumen espiratorio forzado en tres segundos (FEV3)"
label(data$fev6_2) = "Volumen espiratorio forzado en seis segundos (FEV6)"
label(data$error_espirometria_2) = "Error"
label(data$espirometria_aceptable_2) = "¿Aceptable?"
label(data$espirometria_3) = "¿Realizada?"
label(data$fvc_3) = "Capacidad vital forzada (CVF o FVC)"
label(data$fev1_3) = "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
label(data$fev1_fvc_3) = "FEV1/FVC"
label(data$pef_3) = "Flujo espiratorio máximo (PEF o FEF)"
label(data$fev3_3) = "Volumen espiratorio forzado en tres segundos (FEV3)"
label(data$fev6_3) = "Volumen espiratorio forzado en seis segundos (FEV6)"
label(data$error_espirometria_3) = "Error"
label(data$espirometria_aceptable_3) = "¿Aceptable?"
label(data$espirometria_4) = "¿Realizada?"
label(data$fvc_4) = "Capacidad vital forzada (CVF o FVC)"
label(data$fev1_4) = "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
label(data$fev1_fvc_4) = "FEV1/FVC"
label(data$pef_4) = "Flujo espiratorio máximo (PEF o FEF)"
label(data$fev3_4) = "Volumen espiratorio forzado en tres segundos (FEV3)"
label(data$fev6_4) = "Volumen espiratorio forzado en seis segundos (FEV6)"
label(data$error_espirometria_4) = "Error"
label(data$espirometria_aceptable_4) = "¿Aceptable?"
label(data$espirometria_5) = "¿Realizada?"
label(data$fvc_5) = "Capacidad vital forzada (CVF o FVC)"
label(data$fev1_5) = "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
label(data$fev1_fvc_5) = "FEV1/FVC"
label(data$pef_5) = "Flujo espiratorio máximo (PEF o FEF)"
label(data$fev3_5) = "Volumen espiratorio forzado en tres segundos (FEV3)"
label(data$fev6_5) = "Volumen espiratorio forzado en seis segundos (FEV6)"
label(data$error_espirometria_5) = "Error"
label(data$espirometria_aceptable_5) = "¿Aceptable?"
label(data$espirometria_6) = "¿Realizada?"
label(data$fvc_6) = "Capacidad vital forzada (CVF o FVC)"
label(data$fev1_6) = "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
label(data$fev1_fvc_6) = "FEV1/FVC"
label(data$pef_6) = "Flujo espiratorio máximo (PEF o FEF)"
label(data$fev3_6) = "Volumen espiratorio forzado en tres segundos (FEV3)"
label(data$fev6_6) = "Volumen espiratorio forzado en seis segundos (FEV6)"

label(data$error_espirometria_6) = "Error"
label(data$espirometria_aceptable_6) = "¿Aceptable?"
label(data$espirometria_7) = "¿Realizada?"
label(data$fvc_7) = "Capacidad vital forzada (CVF o FVC)"
label(data$fev1_7) = "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
label(data$fev1_fvc_7) = "FEV1/FVC"
label(data$pef_7) = "Flujo espiratorio máximo (PEF o FEF)"
label(data$fev3_7) = "Volumen espiratorio forzado en tres segundos (FEV3)"
label(data$fev6_7) = "Volumen espiratorio forzado en seis segundos (FEV6)"
label(data$error_espirometria_7) = "Error"
label(data$espirometria_aceptable_7) = "¿Aceptable?"
label(data$espirometria_8) = "¿Realizada?"
label(data$fvc_8) = "Capacidad vital forzada (CVF o FVC)"
label(data$fev1_8) = "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
label(data$fev1_fvc_8) = "FEV1/FVC"
label(data$pef_8) = "Flujo espiratorio máximo (PEF o FEF)"
label(data$fev3_8) = "Volumen espiratorio forzado en tres segundos (FEV3)"
label(data$fev6_8) = "Volumen espiratorio forzado en seis segundos (FEV6)"
label(data$error_espirometria_8) = "Error"
label(data$espirometria_aceptable_8) = "¿Aceptable?"
label(data$razon_detener) = "Razón para detenerse"
label(data$razon_otros) = "Si Otro (especifique)"
label(data$fecha_revision) = "Fecha de revisión"
label(data$revision_curvas) = "¿Hay al menos 3 curvas aceptables y 2 reproducibles? "
label(data$fvc_revision) = "Capacidad vital forzada (CVF o FVC)"
label(data$fev1_revision) = "Volumen espiratorio forzado en el primer segundo (VEF1 o FEV1)"
label(data$fev1_fvc_revision) = "FEV1/FVC"
label(data$pef_revision) = "Flujo espiratorio máximo (PEF o FEF)"
label(data$fev3_revision) = "Volumen espiratorio forzado en tres segundos (FEV3)"
label(data$fev6_revision) = "Volumen espiratorio forzado en seis segundos (FEV6)"
label(data$clasificacion_revision) = "Calificación: espirometría"
label(data$encuestador_6) = "Encuestador"
label(data$fecha_hora_6) = "Fecha y hora (fin)"
label(data$comentario_espirometria_6) = "Comentario adicional"
label(data$cuestionario_adolescentes_vi_espirometra_complete) = "Complete?"
label(data$formulario_final) = "¿Qué encuestador completó el formulario?"
label(data$fecha_hora_fin) = "Fecha y hora de fin"
label(data$fin_de_cuestionarios_complete) = "Complete?"

